### ISSUE TITLE
SQL Server connections should use backslash after domain

### ISSUE THREAD

**Issue by mav7014** [OHDSI/DatabaseConnector#10]
This was brought up in [this post](http://forums.ohdsi.org/t/have-problem-to-use-the-module-databaseconnector/461/3) in our Developers forum. DatabaseConnector currently expects forward slashes (i.e. domain/username) whereas Windows always uses back slashes (i.e. domain\username). As an alternate solution, DatabaseConnector may use a separate parameter for domain.

**Comment by schuemie** [comment]
I went for the separate parameter option (see 454f648a53c9771ae09a0c1010363a9ac7f7316d).
