### ISSUE TITLE
Change parameter schema to databaseSchema

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/DatabaseConnector#109]
https://github.com/OHDSI/DatabaseConnector/blob/aedc5e8ae001db7aa3b4ea04a76ef744174f0fd5/R/Connect.R#L64

I think, this parameter needs to be changed to databaseSchema based on this discussion

https://github.com/OHDSI/SkeletonComparativeEffectStudy/pull/28#discussion_r380235591

**Comment by schuemie** [comment]
Either that or we remove it altogether. DatabaseConnector will try to set the current database / schema to what the user specifies here, but not all platforms support setting a current database / schema. For example, Azure (SQL Server in the cloud) [doesn't support the `USE` statement](https://docs.microsoft.com/en-us/sql/t-sql/language-elements/use-transact-sql?view=sql-server-ver15).

**Comment by gowthamrao** [comment]
I would recommend we remove schema altogether. In addition to your point, co-existing, schema & databaseSchema in same package is confusing.

**Comment by schuemie** [comment]
Ok, in that case the first step is to deprecate the schema argument. Would you like to create a pull request (to the develop branch)? [Here](https://github.com/OHDSI/CohortMethod/commit/2ee710ed093a2859a5b1c40398bb4a5961519c8b#diff-f635b8ed5cd9384e1274a7b68c2dcd07)'s an example of me deprecating some arguments. In brief, we need to 

1. Change the documentation to say the argument is deprecated, and what users are expected to do instead (in this case use explicit references to the database or schema in their SQL, like `SELECT * FROM my_schema.my_table;`).
2. Throw a warning if someone uses the argument, telling them the argument will no longer be supported in future versions of DatabaseConnector.

**Comment by gowthamrao** [comment]
@schuemie yes, i will attempt to make contribution to DatabaseConnector package
