### ISSUE TITLE
insertTable fails on BigQuery

### ISSUE THREAD

**Issue by CartWill** [OHDSI/DatabaseConnector#113]
The insertTable function fails on BigQuery when trying to insert a dataframe as a table.  Throws a JDBC driver error that batched and streamed parameters are not supported.   
```
DatabaseConnector::insertTable(connection = connection, tableName = "results.testTable", data=df, createTable = TRUE, tempTable = FALSE)
java.sql.SQLException: [Simba][BigQueryJDBCDriver](100036) Batched and streamed parameters not supported.
	at com.simba.googlebigquery.googlebigquery.dataengine.BQAbstractExecutor.clearPushedParamData(Unknown Source)
	at com.simba.googlebigquery.jdbc.common.SPreparedStatement.doClearBatch(Unknown Source)
	at com.simba.googlebigquery.jdbc.common.SPreparedStatement.clearBatch(Unknown Source)
	at com.simba.googlebigquery.jdbc.common.SPreparedStatement.executePreparedAnyBatch(Unknown Source)
	at com.simba.googlebigquery.jdbc.common.SPreparedStatement.executeBatch(Unknown Source)
Caused by: com.simba.googlebigquery.support.exceptions.GeneralException: [Simba][BigQueryJDBCDriver](100036) Batched and streamed parameters not supported.
	... 5 more
```

The OHDSI/DataQualityDashboard uses this to try to insert the results as a table : https://github.com/OHDSI/DataQualityDashboard/issues/98#issuecomment-595951134

**Comment by schuemie** [comment]
Who currently supports BigQuery? @pavgra?

**Comment by konstjar** [comment]
@schuemie could you please assign to @wivern

**Comment by CartWill** [comment]
I tried this recently and get a slightly different error.

```
insertTable(connection = conn,
            tableName = paste0(target_database_schema,".specific_patients", sep="", collapse = ""),
            data = specific_patients,
            dropTableIfExists = TRUE,
            createTable = TRUE,
            tempTable = FALSE,
            useMppBulkLoad = FALSE)
```
Error:

> DBMS:
> bigquery
> 
> Error:
> java.sql.SQLException: [Simba][BigQueryJDBCDriver](100032) Error executing query job. Message: Table name "goa4w87euwvtrfemqcgnlrjrknab" missing dataset while no default dataset is set in the request.
> 
> SQL:
> CREATE TABLE goa4w87euwvtrfemqcgnlrjrknab  AS WITH data   as ...

Even though tempTable is set to false, it looks like it's trying to insert the table with a random, temporary name.

**Comment by konstjar** [comment]
I think you missed to define parameter called `oracleTempSchema`. BigQuery database does not support temp tables in the way that packages expect it. That's why it's better to create separate  BigQuery dataset as temp one and define it as `oracleTempSchema` parameter.
