### ISSUE TITLE
Support SSAS?

### ISSUE THREAD

**Issue by happyshows** [OHDSI/DatabaseConnector#12]
Hi,

I'm interested to know if this package support or will support connecting to data cube in SSAS?

**Comment by schuemie** [comment]
Unfortunately, DatabaseConnector does not support SSAS. None of the developers (mostly me) currently has a business need for SSAS, or even access to SSAS for testing purposes, so there are no plans to add it.

**Comment by happyshows** [comment]
Alright, thanks.
