### ISSUE TITLE
InsertTable function needs databaseSchema?

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/DatabaseConnector#123]
https://github.com/OHDSI/DatabaseConnector/blob/41bc1aef48c6c0be64bca7c12ab9e6591d5f5ab0/R/InsertTable.R#L250

schema parameter is deprecated. How do we specify the target databaseSchema in insertTable function. Example here implies that the tableName is full name https://github.com/OHDSI/DatabaseConnector/blob/41bc1aef48c6c0be64bca7c12ab9e6591d5f5ab0/R/InsertTable.R#L242 If yes, needs clarification in documentation

**Comment by schuemie** [comment]
Yes, must be full name

**Comment by schuemie** [comment]
To avoid confusion, it might make sense to add a `databaseSchema` argument. Under the hood this would simply be concatenated with the table name (using a period as separator).

**Comment by gowthamrao** [comment]
Yes , and we need to deprecate this
https://github.com/OHDSI/DatabaseConnector/blob/41bc1aef48c6c0be64bca7c12ab9e6591d5f5ab0/R/Connect.R#L63

**Comment by gowthamrao** [comment]
Similar situation with function `dbExistsTable`

It still accepts 

> database	Name of the database.
> schema	Name of the schema.


Might be useful to add databaseSchema, and remove database and schema

**Comment by schuemie** [comment]
Added in v4.0.0
