### ISSUE TITLE
Issue with data type and the names of colums of dataframe

### ISSUE THREAD

**Issue by alexfsil** [OHDSI/DatabaseConnector#128]
Hi, here I will detail the weaknesses that I have found doing insert with the `insertTable()` function.

1. When the columns of my dataframe are of the style ("Id" , "Name") that matches with the style of the table (called "People"). I'm getting the following error:  

> "ERROR: column "id" of relation "People" does not exist"

Is there any way to keep the name of the column and **not transform it into lowercase**?

2. Problem with data type. In the "People" table the data type of the "Id" column is uuid. In the dataframe of R the column is of type character. 
I'm getting the following error:  

> ERROR: column "id" is of type uuid but expression is of type character varying

Is there the possibility of being able the **type of data with which to make the insert**? 

Thank you very much

**Comment by schuemie** [comment]
1. What database platform are you using? I thought all platforms were case-insensitive as it relates to table and field names.

2. UUID is not a native R data type, so it isn't strange that DatabaseConnector doesn't know how to handle it. Couldn't you convert the column to a character type (using `as.character()`) before inserting?

**Comment by alexfsil** [comment]
1. The database platform I am using is postgreSQL, but when the database was created the entities (table names, columns,..) were specified in quotes and for that reason it is case sensitive. 
In this link is explained:  [https://stackoverflow.com/questions/21796446/postgres-case-sensitivity#:~:text=In%20PostgreSQL%20unquoted%20names%20are%20case%2Dinsensitive.&text=Thus%2C%20when%20creating%20entities%20(tables,or%20quoted%2Dbut%2Dlowercased.](url)

2. This is true, since in the dataframe the column "Id" is of character type. The problem is that in the PostgreSQL table the type of the column "Id" is uuid so it does not allow to insert another kind of data, in this case character.

This way it can be solved, but the code is less readable and more tedious to work 

```
query <- paste0('INSERT INTO "dbo"."People" VALUES (\'', Id ,'\'::UUID)')
executeSql(con_postgre,query)
```

**Comment by schuemie** [comment]
I'm sorry, but I'm going to declare both issues out of scope. The central idea to DatabaseConnector is that it provides an identical experience for all database platforms (especially when combined with SqlRender). Software that use these package automatically run on all database platforms. 

Case-sensitivity and UUID fields are highly specific to one platform only, and therefore do not fit this idea.

For platform-specific support, I highly recommend [RPostgreSQL](https://cran.r-project.org/web/packages/RPostgreSQL/index.html). Alternatively, there's [RJDBC](https://cran.r-project.org/web/packages/RJDBC/index.html).

**Comment by alexfsil** [comment]
Okay, thank you very much for the support.
