### ISSUE TITLE
What happened to dbGetQueryPostgreSql and dbGetQuery.ffdf?

### ISSUE THREAD

**Issue by jmbanda** [OHDSI/DatabaseConnector#13]
Latest version seems to effectively remove both functions and the only one available is querySql. This effectively breaks the Aphrodite code that depends on database calls. 

Did I miss a notice that this change will be made?

**Comment by schuemie** [comment]
They have been renamed to `lowLevelQuerySql` and `lowLevelQuerySql.ffdf`, respectively. Preferably, people should use `querySql` and `querySql.ffdf` instead.

**Comment by jmbanda** [comment]
Got it, it was a bit sudden. I have changed Aphrodite to use querySql.

Thanks!

_____________________________________________________________
Juan M. Banda, Ph.D.
Postdoctoral Scholar - Center for Biomedical Informatics Research
Stanford University School of Medicine

Website: http://www.jmbanda.com | Google Scholar: http://goo.gl/RiO2jY
ResearchGate: http://goo.gl/7C31uc | DBLP: http://goo.gl/BBvmJj
LinkedIn: http://goo.gl/h95tnq
