### ISSUE TITLE
errorReportSql.txt file opening mode

### ISSUE THREAD

**Issue by scossin** [OHDSI/DatabaseConnector#132]
While using the package https://github.com/EHDEN/CatalogueExport I have noticed that DatabaseConnector::executeSql() has been writing SQL errors to a file (default errorReportSql.txt) by using the default opening mode "w+":

```R
fileConn <- file(fileName)
```
> If for a file or (on most platforms) a fifo connection the description is "", the file/fifo is immediately opened (in "w+" mode unless open = "w+b" is specified) 

The problem is, if multiple errors are generated by the function, the next error will overwrite the previous one without warning. I would like to suggest to open the error file with opening mode "a":

```R
fileConn <- file(fileName, open="a")
```
> Open for writing.  The file is created if it does not exist.  The
         stream is positioned at the end of the file. 

I will make a pull request https://github.com/scossin/DatabaseConnector/commit/94b3e4cc38490363507e5418c6bdfd010dc8df60 if you agree

**Comment by schuemie** [comment]
The idea is the program should stop after an error. That way, the error report will be on the error that broke the program. I recommend changing the program to either not throw errors all the time, or to stop at the first error,

**Comment by PRijnbeek** [comment]
I agree with @schuemie. We can fix this, please make in issue in the CatalogueExport package and we we can solve this there.

**Comment by scossin** [comment]
Ok thanks, I close this issue then.
