### ISSUE TITLE
Issue with driver folder that has jar in the name

### ISSUE THREAD

**Issue by PRijnbeek** [OHDSI/DatabaseConnector#135]
it could not find the drivers due to this line when I used d:/dbjar as folder

https://github.com/OHDSI/DatabaseConnector/blob/0ab0ddfa4299ffd4d0c66d84640a5fe4fb831efd/R/Drivers.R#L137

**Comment by schuemie** [comment]
Thanks. The new behavior will be to throw an informative error when the user points to a file instead of a folder. We won't try to silently fix it.

**Comment by PRijnbeek** [comment]
what do you mean d:/dbjar was the folder name.

**Comment by schuemie** [comment]
Yes, but DatabaseConnector erroneously thought it was a file because it ended with 'jar'. I've now removed that check, and it throws an error if the path you provide points to an existing file.

**Comment by PRijnbeek** [comment]
Ah ok yes got it thanks
