### ISSUE TITLE
Using User-Level .Renviron vs Project-Level .Renviron settings files

### ISSUE THREAD

**Issue by anthonysena** [OHDSI/DatabaseConnector#136]
Posting this since others may find this helpful (since it took me a couple minutes to figure out) and to see if there is a better way to approach my R configuration.

Using DatabaseConnector V4, I've set up a folder `"D:/jdbcDrivers"` to hold my JDBC drivers. I then made this my default when starting up R by calling:

```r
> usethis::edit_r_environ()
* Modify 'C:/Users/admin_asena5/Documents/.Renviron'
* Restart R for changes to take effect
```

I then added `DATABASECONNECTOR_JAR_FOLDER = "D:/jdbcDrivers"`, to the settings file: `'C:/Users/admin_asena5/Documents/.Renviron'`. I then restarted RStudio and things worked well. 

Later, I opened an R project that also included an `.Renviron` settings file. When I went to use DatabaseConnector, it was unable to find the JDBC drivers. I incorrectly assumed that my project `.Renviron` settings would inherit all values from my user-level `.Renviron`. Unfortunately that is not the case as described in more detail in this [RStudio Support article](https://support.rstudio.com/hc/en-us/articles/360047157094-Managing-R-with-Rprofile-Renviron-Rprofile-site-Renviron-site-rsession-conf-and-repos-conf). Once I addded  `DATABASECONNECTOR_JAR_FOLDER = "D:/jdbcDrivers"` to my project .Renviron file, things worked again.

I'm open to alternative configuration options if they exist.

**Comment by schuemie** [comment]
Thanks! I guess we would like to recommend against project-specific .Renviron files in general. (You would also lose your GITHUB_PAT and PATH to RTools).

**Comment by schuemie** [comment]
Closing issue as there's no action we can take to prevent this.
