### ISSUE TITLE
Unlist converts date to integer

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/DatabaseConnector#137]
https://github.com/OHDSI/DatabaseConnector/blob/0ab0ddfa4299ffd4d0c66d84640a5fe4fb831efd/R/InsertTable.R#L323

```
data <- jsonlite::fromJSON(txt = '[{"concept_id_1":192671,"concept_id_2":35208414,"relationship_id":"Mapped from","valid_start_date":"1970-01-01","valid_end_date":"2099-12-31"},{"concept_id_1":35208414,"concept_id_2":192671,"relationship_id":"Maps to","valid_start_date":"1970-01-01","valid_end_date":"2099-12-31"}] ') %>% 
  dplyr::tibble() %>% 
  dplyr::mutate(valid_start_date = lubridate::as_date(.data$valid_start_date),
                valid_end_date = lubridate::as_date(.data$valid_end_date))
```
`
unlist(data[1:2, i], use.names = FALSE)
`
> [1] 0 0

leads to this error

> _class_id,standard_concept,concept_code,valid_start_date,valid_end_date,invalid_reason) VALUES(35208414,'Gastrointestinal hemorrhage, unspecified','Condition','ICD10CM','4-char billing code',NULL,'K92.2',13514.0,47481.0,NULL) was aborted: ERROR: column "valid_start_date" is of type date but expression is of type double precision
>   Hint: You will need to rewrite or cast the expression.
>   Position: 203  Call getNextException to see other errors in the batch.
> 	at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:169)
> 	at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:854)
> 	at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:893)
> 	at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1644)
> 	at org.ohdsi.databaseConnector.BatchedInsert.executeBatch(BatchedInsert.java:114)
> Caused by: org.postgresql.util.PSQLException: ERROR: column "valid_start_date" is of type date but expression is of type double precision
>   Hint: You will need to rewrite or cast the expression.
>   Position: 203
> 	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2553)
> 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2285)
> 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:323)
> 	at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:851)
> 	... 3 more
> ERROR: column "valid_start_date" is of type date but expression is of type double precision
>   Hint: You will need to rewrite or cast the expression.
>   Position: 203

**Comment by gowthamrao** [comment]
This only happens in a tibble not a dataframe

```
data <- jsonlite::fromJSON(txt = '[{"concept_id_1":192671,"concept_id_2":35208414,"relationship_id":"Mapped from","valid_start_date":"1970-01-01","valid_end_date":"2099-12-31"},{"concept_id_1":35208414,"concept_id_2":192671,"relationship_id":"Maps to","valid_start_date":"1970-01-01","valid_end_date":"2099-12-31"}] ') %>% data <- jsonlite::fromJSON(txt = '[{"concept_id_1":192671,"concept_id_2":35208414,"relationship_id":"Mapped from","valid_start_date":"1970-01-01","valid_end_date":"2099-12-31"},{"concept_id_1":35208414,"concept_id_2":192671,"relationship_id":"Maps to","valid_start_date":"1970-01-01","valid_end_date":"2099-12-31"}] ') %>% 
  dplyr::mutate(valid_start_date = lubridate::as_date(.data$valid_start_date),
                valid_end_date = lubridate::as_date(.data$valid_end_date))
```


`unlist(data[1:2, 4], use.names = FALSE)`

> [1] "1970-01-01" "1970-01-01"

**Comment by gowthamrao** [comment]
my proposal was to replace unlist with `do.call("c", data[start:end, i])`

but looks like there might already be a fix in develop 

https://github.com/OHDSI/DatabaseConnector/blob/develop/R/InsertTable.R#L323-L326

**Comment by schuemie** [comment]
Yes, in general R tends to convert dates to integers at random points :-( The develop-branch fix should address it here.

**Comment by gowthamrao** [comment]
Thanks @schuemie

**Comment by gowthamrao** [comment]
Keeping it open it next release of DatabaseConnector is in CRAN
