### ISSUE TITLE
CDP Impala JDBC driver requires use of JDBC41 driver. 

### ISSUE THREAD

**Issue by harrica** [OHDSI/DatabaseConnector#142]
I'm trying to use an impala Data Warehouse Experience on the Cloudera Data Platform and the driver that is in the required connection is jdbc41 and there doesn't seem to be a way to override.  Am I missing something?

Thanks

**Comment by schuemie** [comment]
I'm not sure there currently is anybody providing support for Impala. I have allowed others to implement Impala support, but the last pull request I got for Impala is 4 years old.

**Comment by harrica** [comment]
Ok then I’ll have a go, not to support but to see if I can make it work.

Cheers


Richard Harvey
***@***.***
