### ISSUE TITLE
dbGetQuery return integer instead of decimal

### ISSUE THREAD

**Issue by illoRocks** [OHDSI/DatabaseConnector#143]
Hi,

I have had a problem with decimal numbers since updating from version 3.X to 4.0.2.
When I try to get a decimal number from an Oracle database, I get an integer. The number is converted to a non-rounded integer.

Here is an example:
```
library(DatabaseConnector)

connectionDetails <- createConnectionDetails(
  dbms = "oracle",
  connectionString = "jdbc:oracle:thin:@//...",
  user = "user",
  password = "pw"
)

conn <- connect(connectionDetails)

dbGetQuery(conn, "select 1/10 as A, 9/10 as B from dual")
```

The result is
```
   A B
1 0 0
```
But the result shold be
```
     A    B
1 0.1 0.9
```

The drive was downloaded by downloadJdbcDrivers.

Thanks

**Comment by schuemie** [comment]
Thanks!

Oracle does things a bit differently when it comes to data types, so I see I got it wrong. I just pushed a [commit](https://github.com/OHDSI/DatabaseConnector/commit/43239b11999639e93c2153f2eb91e58d3e7de3c5) to the develop branch that should fix it. If you want, you can try it out by running
```r
install.packages("remotes")
remotes::install_github("ohdsi/DatabaseConnector", ref = "develop")
```

It will be included in the next release, which hasn't been scheduled yet.

**Comment by illoRocks** [comment]
It works. Thank You!

**Comment by illoRocks** [comment]
I found an other bug releated to this problem. This example is made by the current development version.

`
dbGetQuery(conn, "
  SELECT
      1/10 as A,
      X1,
      X2,
      X1 / X2 as B
  FROM (
      SELECT
        1 as X1,
        10 as X2
      FROM
          DUAL
    )
")
`

The issue is on column B
`
    A X1 X2 B
1 0.1  1 10 0
`

The result should be:
`
    A X1 X2   B
1 0.1  1 10 0.1
`

The curious thing is when I execute the same statement, without selecting X1 and X2, I get the correct result.
`
dbGetQuery(conn, "
  SELECT
      1/10 as A,
      X1 / X2 as B
  FROM (
      SELECT
        1 as X1,
        10 as X2
      FROM
          DUAL
    )
")
`

`
    A    B
1 0.1 0.1
`

**Comment by schuemie** [comment]
Might this be a 'feature' on the Oracle side? X1 and X2 are probably internally cast as integers, and dividing two integers produces an integer? What if you run this code directly against an Oracle instance, so not using DatabaseConnector?

**Comment by illoRocks** [comment]
This is not a feature of Oracle.  I got the correct result by executing the first sql in my last comment.

![image](https://user-images.githubusercontent.com/26260521/117973731-07c23380-b32d-11eb-9e08-bbe45f72e2e8.png)

**Comment by schuemie** [comment]
The JDBC driver is telling me B is an integer (scale = 0, precision = 0). This seems like a bug in the driver. The only option I see is to always interpret every number as a double, which was the past behavior. That does not seem like a pretty solution.

**Comment by illoRocks** [comment]
Hi,

the problem still exists on version 5.0.4.

The following code return an incorrect value at column 4:
```
dbGetQuery(conn, "
  SELECT
      1/10 as A,
      X1,
      X2,
      X1 / X2 as B
  FROM (
      SELECT
        1 as X1,
        10 as X2
      FROM
          DUAL
    )
")

    A X1 X2 B
1 0.1  1 10 0
```
The result on column B should be 0.1.


I cloned this repo and build a new jar file. I removed one OR in the if statement in line [116](https://github.com/OHDSI/DatabaseConnector/blob/3b7c5a661405479d51bd230611cdedc1ba7d69b3/java/org/ohdsi/databaseConnector/BatchedQuery.java#L116). With this difference I was able to get the correct result of the statement above.

From 
```
if (type == Types.INTEGER || type == Types.SMALLINT || type == Types.TINYINT
    || (dbms.equals("oracle") && className.equals("java.math.BigDecimal") && precision != 19 && scale == 0))
         columnTypes[columnIndex] = INTEGER;
```
To
```
if (type == Types.INTEGER || type == Types.SMALLINT || type == Types.TINYINT)
         columnTypes[columnIndex] = INTEGER;
```
After this change the result of column B was 0.1

For more information I have some screenshots of the variables in the for loop:

First Column (A)
![image](https://user-images.githubusercontent.com/26260521/176545045-ae944d12-bc50-45ec-b468-484936efc791.png)

Second Column (X1)
![image](https://user-images.githubusercontent.com/26260521/176545129-4eddebee-fedc-4dd3-bec1-d12f9163f34d.png)

Third Column (X2)
![image](https://user-images.githubusercontent.com/26260521/176545322-2e756c0c-7771-45dd-9474-c2597c6be76b.png)

Fourth Column (B)
![image](https://user-images.githubusercontent.com/26260521/176545420-b6683c54-b39c-4b4d-aaa0-4d6a57f6c1d1.png)


Unfortunately I don't have the right setup to pass all tests. Therefore I would not make a PR. I hope this can help you :)
