### ISSUE TITLE
Can cached JDBC drivers be used for package tests?

### ISSUE THREAD

**Issue by ablack3** [OHDSI/DatabaseConnector#146]
Each time I run one or more tests the JDBC drivers are redownloaded to a new temp directory. See https://github.com/OHDSI/DatabaseConnector/blob/master/tests/testthat/setup.R 

Would it be better to only download the drivers if they do not currently exist in `DATABASECONNECTOR_JAR_FOLDER` or are not the latest version of the drivers?

**Comment by schuemie** [comment]
Well, I do want some code that tests the downloading of the drivers. I guess running the tests on a local machine might not need to download the drivers every time the unit tests are executed.
