### ISSUE TITLE
Error with drop table if exists on big query

### ISSUE THREAD

**Issue by ablack3** [OHDSI/DatabaseConnector#151]
Relates to https://github.com/r-dbi/bigrquery/issues/357

It seems that drop table if exists does not work on bigquery. 

@Sulieman.Lina@gmail.com will you post an example?

**Comment by Linasulieman** [comment]
@ablack3 : I attached two examples: one for creating table and one for dropping table. Both of them gave the same error.

<img width="1044" alt="CreateTableBigQuery" src="https://user-images.githubusercontent.com/4141002/126012772-76040ef0-b12f-4533-b060-4272d2998c39.png">
<img width="1025" alt="DropBigQuery" src="https://user-images.githubusercontent.com/4141002/126012777-e3df4352-9199-4c0d-9c3c-0832cbefb273.png">

**Comment by schuemie** [comment]
As the error message indicates, `querySql` expects a result to be returned, but these SQL statements do not generate a result.

Please use [`executeSql()`](http://ohdsi.github.io/DatabaseConnector/reference/executeSql.html) instead.
