### ISSUE TITLE
java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by schuemie** [OHDSI/DatabaseConnector#154]
Moving from [this issue in Andromeda](https://github.com/OHDSI/Andromeda/issues/26).

@jreps: would you be able to provide a reproducible example that runs quickly?

**Comment by schuemie** [comment]
Just thinking out loud, but one possible cause could be the RedShift JDBC driver. Once we have a (easily) reproducible example we may consider updating the driver first.

**Comment by azimov** [comment]
I was having some similar issues when running a large SCC analysis, I updated the java parameters before connecting a Database to change the garbage collection and increase the memory limit

```
options(java.parameters = c("-XX:+UseConcMarkSweepGC", "-Xmx8192m"))
```
It seems to work now.
This isn't a solution that can be added to the package though...

**Comment by schuemie** [comment]
Please don't ever propose solutions like this. They have a habit of never going away. I still see 'fixes' for issues that were solved many years ago in people's scripts today.

DatabaseConnector should just work with the memory it has. The Java heap is only used to pass through batches from the JDBC driver to R.

**Comment by DrTTrousers** [comment]
@schuemie Sorry to resurrect a quiet issue but I've got a possibly related (Pasted below)

This was when trying to run the CORAZON study package (https://github.com/ohdsi-studies/Corazon) 
I've tried maxCores <-1, generating cohorts in one job then just running the analysis. It throws this same error immediately as soon as it tries to insert the tables (I think!)

java.sql.SQLException: [Amazon](500310) Invalid operation: Out Of Memory:  
Details: -----------------------------------------------
  error:  Out Of Memory: 
  code:      1004
  context:   alloc(131072,MtCgBlock)
  query:     13482342
  location:  alloc.cpp:493
  process:   padbmaster [pid=15569]
  -----------------------------------------------;

Backtrace:
     ▆
  1. └─global sourceWithProgress(...)
  2.   └─base::eval(statements[[idx]], envir = sourceEnv)
  3.     └─base::eval(statements[[idx]], envir = sourceEnv)
  4.       └─corazon::execute(...)
  5.         └─corazon::runCohortMethod(...)
  6.           └─CohortMethod::runCmAnalyses(...)
  7.             └─ParallelLogger::clusterApply(cluster, objectsToCreate, createCmDataObject)
  8.               └─base::lapply(x, fun, ...)
  9.                 └─CohortMethod FUN(X[[i]], ...)
 10.                   ├─base::do.call("getDbCohortMethodData", params$args)
 11.                   └─CohortMethod::getDbCohortMethodData(...)
 12.                     └─FeatureExtraction::getDbCovariateData(...)
 13.                       ├─base::do.call(eval(parse(text = fun)), args)
 14.                       └─FeatureExtraction `<fn>`(...)
 15.                         ├─DatabaseConnector::insertTable(...)
 16.                         └─DatabaseConnector:::insertTable.default(...)
 17.                           └─DatabaseConnector:::ctasHack(...)
 18.                             └─DatabaseConnector::executeSql(...)
 19.                               └─base::tryCatch(...)
 20.                                 └─base tryCatchList(expr, classes, parentenv, handlers)
 21.                                   └─base tryCatchOne(expr, names, parentenv, handlers[[1L]])
 22.                                     └─value[[3L]](cond)
 23.                                       └─DatabaseConnector:::.createErrorReport(...)
 24.                                         └─rlang::abort(...)

**Comment by schuemie** [comment]
Huh, this is actually the RedShift cluster saying it is out of memory, not your machine running R. Maybe your RedShift cluster needs to be scaled up? Could you talk to your RedShift admin?

**Comment by DrTTrousers** [comment]
Thanks for the confirmation @schuemie

**Comment by lcpinheiro** [comment]
Hey @schuemie, I have bumped into the same error as the OP (same SQL code causing same java heap space issue) on a Databricks Spark JDBC connection. 

Looking at the thread of this issue I'm wondering how to address this, am I missing a debugging/settings step here? FYI, the same SQL code runs fine with an ODBC connection.

**Comment by schuemie** [comment]
Hi @lcpinheiro . Just to confirm, you're getting a 

```java.sql.SQLException: Amazon Invalid operation: Out Of Memory:```

error from a Databricks server?

**Comment by lcpinheiro** [comment]
Hi @schuemie, I have the spark version of that I suppose:

```
DBMS:
spark

Error:
java.lang.OutOfMemoryError: Java heap space

SQL:
SELECT *
FROM (
SELECT row_id, covariate_id, covariate_value FROM hive_metastore.temp_db.m8r7o5s9cov_1 UNION ALL
SELECT row_id, covariate_id, covariate_value FROM hive_metastore.temp_db.m8r7o5s9cov_2 UNION ALL
SELECT row_id, covariate_id, covariate_value FROM hive_metastore.temp_db.m8r7o5s9cov_3 UNION ALL
SELECT row_id, covariate_id, covariate_value FROM hive_metastore.temp_db.m8r7o5s9cov_4 UNION ALL
SELECT row_id, covariate_id, covariate_value FROM hive_metastore.temp_db.m8r7o5s9cov_5 UNION ALL
SELECT row_id, covariate_id, covariate_value FROM hive_metastore.temp_db.m8r7o5s9cov_6 UNION ALL
SELECT row_id, covariate_id, covariate_value FROM hive_metastore.temp_db.m8r7o5s9cov_7 UNION ALL
SELECT row_id, covariate_id, covariate_value FROM hive_metastore.temp_db.m8r7o5s9cov_8 UNION ALL
SELECT row_id, covariate_id, covariate_value FROM hive_metastore.temp_db.m8r7o5s9cov_9 UNION ALL
SELECT row_id, covariate_id, covariate_value FROM hive_metastore.temp_db.m8r7o5s9cov_10 UNION ALL
SELECT row_id, covariate_id, covariate_value FROM hive_metastore.temp_db.m8r7o5s9cov_11 UNION ALL
SELECT row_id, covariate_id, covariate_value FROM hive_metastore.temp_db.m8r7o5s9cov_12 UNION ALL
SELECT row_id, covariate_id, covariate_value FROM hive_metastore.temp_db.m8r7o5s9cov_13 UNION ALL
SELECT row_id, covariate_id, covariate_value FROM hive_metastore.temp_db.m8r7o5s9cov_14 UNION ALL
SELECT row_id, covariate_id, covariate_value FROM hive_metastore.temp_db.m8r7o5s9cov_15 UNION ALL
SELECT row_id, covariate_id, covariate_value FROM hive_metastore.temp_db.m8r7o5s9cov_16 UNION ALL
SELECT row_id, covariate_id, covariate_value FROM hive_metastore.temp_db.m8r7o5s9cov_17 UNION ALL
SELECT row_id, covariate_id, covariate_value FROM hive_metastore.temp_db.m8r7o5s9cov_18 UNION ALL
SELECT row_id, covariate_id, covariate_value FROM hive_metastore.temp_db.m8r7o5s9cov_19 UNION ALL
SELECT row_id, covariate_id, covariate_value FROM hive_metastore.temp_db.m8r7o5s9cov_20 UNION ALL
SELECT row_id, covariate_id, covariate_value FROM hive_metastore.temp_db.m8r7o5s9cov_21 UNION ALL
SELECT row_id, covariate_id, covariate_value FROM hive_metastore.temp_db.m8r7o5s9cov_22 UNION ALL
SELECT row_id, covariate_id, covariate_value FROM hive_metastore.temp_db.m8r7o5s9cov_23 UNION ALL
SELECT row_id, covariate_id, covariate_value FROM hive_metastore.temp_db.m8r7o5s9cov_24
) all_covariates;

R version:
R version 4.2.1 (2022-06-23 ucrt)

Platform:
x86_64-w64-mingw32

Attached base packages:
- stats
- graphics
- grDevices
- datasets
- utils
- methods
- base

Other attached packages:
- CohortMethod (4.2.2)
- FeatureExtraction (3.2.0)
- Andromeda (0.6.0)
- dplyr (1.0.7)
- Cyclops (3.1.2)
- gibleed (0.0.1)
- DatabaseConnector (5.0.2)
```

**Comment by egillax** [comment]
I think this issue should be re-opened @schuemie 

I can very reliably generate this issue on redshift. Steeps needed to reproduce:

- Use `PatientLevelPrediction::getPlpData` with a large cohort (3+ million) and default set of covariates from FeatureExtraction.

It always error's when fetching the features. I tried to make a more minimal example by creating the tables of features manually and then only doing the fetching but for some reason that worked.  

I've once got this error on `postgres` but I'm not sure that means postgres is also affected since it's a very generic java error.

@schuemie I know you work with huge cohorts on redshift, so I'm curious why you have never run into this. Are you using `cohortMethod` to fetch the data? 

I now see if I'm not mistaken with `DatabaseConnector` 6+  that I could try to use a redshift `ODBC` driver through the DBI interface to try to see if this is indeed the redshift jdbc driver.

**Comment by schuemie** [comment]
There are several important improvements on this front in [version 6.1.0](http://ohdsi.github.io/DatabaseConnector/news/index.html#databaseconnector-610), so be sure to use that one (or newer).

Also, possibly relevant, in my organization we had to switch from Oracle Java to Coretto Java for licensing reasons. Oracle Java by default uses a 2GB heap. Coretto uses only a 512MB heap by default! That is barely enough to hold the RedShift driver, let alone some data. So we have run into this issue more often recently just for that reason alone. A reliable but annoying way to get around that is by setting the heap space to something more reasonable, e.g.:
```r
options(java.parameters = "-Xmx8g")
```
The trick is to run this code before anything else, because as soon as rJava creates the VM (e.g. because DatabaseConnector is loaded) it is too late. For that reason I have that line in my global `.Rprofile` file (run `usethis::edit_r_profile()` to create/edit).
