### ISSUE TITLE
extraSettings (keepalives_*) to connect postgresql via DatabaseConnector::createConnectionDetails

### ISSUE THREAD

**Issue by lofung** [OHDSI/DatabaseConnector#155]
I have an experience in connecting postgresql via Python during ETL processes. When we are uploading some big table or doing very long optimization queries (e.g. cluster on big tables), the connection would time out.

The way I managed to fix this (despite I have no idea why) is:

```
conn = psycopg2.connect(host=“someserver.hk”,
port=12345,
dbname=“ohdsi”,
user=“admin”,
password=“admin1”,
options="-c search_path="+schema,
# it seems the below lines are needed to keep the connection alive.
connect_timeout=10,
keepalives=1,
keepalives_idle=5,
keepalives_interval=2,
keepalives_count=5)
```

I totally do not understand why, but the keepalives lines seem to keep the connection online and the queries would be tolerated to run without a timeout.

Perhaps there is a underlying reason that there is a firewall between my workstation and the server. So if there is no response for too long something would forcefully close the connection.

Anyway I have no idea why it worked but it worked.

-----------

It comes the current problem now. We are told to use R to run a few scripts for the researchers. However, it seems like when the script is automatically running queries against some big tables, the connection would seem to timeout. I do not know about the reason since there is no error log whatsoever.

I can only see that the query is generally vanished from the psql monitor after 1 hour.

So my question is that, in the R package of `DatabaseConnector::createConnectionDetails`, I have read through the documentation and found out that there is a option of `extraSettings`

How can I put those python-like `keepalives_*` settings in the `DatabaseConnector::createConnectionDetails` script?

There seems to have no answers or similar knowledge online.

Thanks

**Comment by schuemie** [comment]
Thanks! Very interesting!

Could you try the following?

```r
details <- createConnectionDetails(
  dbms = "postgresql",
  user = "admin",
  password = "admin1",
  server = "someserver.hk/ohdsi",
  port = 12345,
  extraSettings = "connect_timeout=10;keepalives=1;keepalives_idle=5;keepalives_interval=2;keepalives_count=5"
)

connection <- connect(details)
```

**Comment by lofung** [comment]
Ah I didn't know that the format for extraSettings should be like that. Thanks.

I tried connecting by attaching params at the back like domain.co.uk/database?connect_timeout=10&keepalives=1&keepalives_idle=5

It just does not sound working. Some queries still ran but 117 was still stuck there.


Strangely, I pulled out the stuck SQL. I run them by pasting into my Python connection script wtith all those ````keepalives_*```` stuff, it worked.

**Comment by lofung** [comment]
btw it suspect it could be a Rstudio frontend problem, where the query might have been finished. However the Rstudio freezes where it cannot proceed with the next SQL or display a success message.

However, the R community is really small to look for help :(

**Comment by lofung** [comment]
btw could there be more documentation on ````extraSettings````?

I dunno that it has to be ````;```` instead of a ````,```` and dun really understand how it worked. thanks

**Comment by lofung** [comment]
No,````&tcpKeepAlive=true```` does not work. The query is still stuck at ````ClientRead````. So it is waiting the client to give the next query, but R seems to be not giving it.

**Comment by lofung** [comment]
Changing the connection string worked

````
connectionString = "jdbc:postgresql://localhost:12345/ohdsi_local_test?keepalives=1&keepalives_idle=5&keepalives_interval=2&keepalives_count=5&connect_timeout=10&tcpKeepAlive=true&tcp_keepalives_idle=1&tcp_keepalives_interval=30",
````

and I do not understand why how it really worked
