### ISSUE TITLE
Proposal: Move tempEmulationSchema to connectionDetails

### ISSUE THREAD

**Issue by ablack3** [OHDSI/DatabaseConnector#162]
This proposal is to investigate the idea of moving tempEmulationSchema to connectionDetails and depricating the argument in all of the functions in the HADES analytic packages (all packages not considered "[Supporting Packages](https://ohdsi.github.io/Hades/packages.html)")

The tempEmulationSchema is used to create a temporary write space in database systems that do not support temporary tables. Of the many supported database systems only 3 require the tempEmulationSchema: Oracle, Spark, and Google Big Query.

The tempEmulationSchema argument is only releavant to users who have one of those database systems and is irrelevant to users with any other database system. Thus it is seems natural to treat this as part of the HADES stack that abstracts away differences between database systems (DatabaseConnector and SqlRender). 

If we look at the functions in the analytic packages that use tempEmulationSchema all of them also require connectionDetails since any use of a temp space in a database also requires a connection to the database.

The *exported* functions in HADES that use tempEmulationSchema or the old version oracleTempSchema are:

- PatientLevelPrediction 4.3.10
   - [getPlpData](https://ohdsi.github.io/PatientLevelPrediction/reference/getPlpData.html)
   - similarPlpData() 
   - getPlpTable() 
   - diagnostic()
   - externalValidatePlp()
   - runPlpAnalyses()
- CohortMethod
   -  getDbCohortMethodData()
   - runCmAnalyses()
 - SelfControledCohort
    - runSccAnalyses()
    - runSelfControlledCohort()
- SelfControlledCaseSeries
  - getDbSccsData()
  - runSccsAnalyses() 
- MethodEvaluation
   - createReferenceSetCohorts()
   - computeMdrr()
   - synthesizePositiveControls()
- CohortDiagnostics
   - instantiateCohortSet()
   - runCohortDiagnostics()

I may have accidentally included non-exported functions or missed some expored functions. It seems like all of these functions require both the temp schema and the connection details. I'm thinking that function arguments (especially the first few function arguments) are valuable mental real estate. They quickly tell the user what is important input for the function to work. The tempEmulationSchema is near the first few arguments of many of these analytic functions and only applies to users who have Oracle, Spark, or BigQuery. 

SqlRender also requires tempEmulation Schema to do the translation but is a supporting package that is typically used inside analytic packages. FeatureExtraction::getDbCovariateData() takes a connection so it would still need the tempEmulationSchema as well. 

We could (and currently do) have a layered interface where certain details are abstracted layer. The tempEmulationSchema could be handled at a lower layer and would not need to be surfaced at the analytic layer. This would be a significant API change in HADES but the switch from oracleTempSchema to tempEmulationSchema has not been fully implemented yet so now might be a good time to discuss the option of putting tempEmulationSchema inside connectionDetails.

![image](https://user-images.githubusercontent.com/10227522/135670158-2ca13ebc-9a67-4f64-ae09-db2b34e2f254.png)

@schuemie, @azimov

**Comment by schuemie** [comment]
FYI: the plan was to eventually drop the `tempEmulationSchema` argument, and rely solely on the global R `sqlRenderTempEmulationSchema` option.

Although `tempEmulationSchema` is an argument for SqlRender, and it would be a bit odd to add it to `connectionDetails` which is an argument for DatabaseConnector, I have to admit the two are always used together. Similarly, every call to SqlRender typically used either DatabaseConnector's `connectionDetails` or `connection` object to infer the `dbms` argument. 

If we add `tempEmulationSchema` to `connectionDetails` we should probably also add it to the `connection` object. That way it would always be available when talking to SqlRender (which it typically right before a call to DatabaseConnector).

**Comment by azimov** [comment]
I agree, encapsulating this in the connection seems more natural than something passed on every call as it will be set at the time of connection and never change. (I can imagine the use of `tempEmulationSchema` could also be implemented for pooled database connections, so being able to override the dbms default implementation might be desirable in some limited use cases).

Adam, you also bring up something interesting about the CDM layer- this is implicit in almost all our API usage but could be captured somehow in objects used by SqlRender. I currently use a lot of calls like `do.call(loadRenderTranslateSql myCdmArgs)` but a standard way of capturing not only temp schemas but cdm/vocabulary/results could be beneficial.

**Comment by ablack3** [comment]
So which is a better approach- use a global option or add tempEmulationSchema to connectionDetails and connection? And how do we make a change that affects so many functions in HADES?

**Comment by azimov** [comment]
The use of global options seems less appealing to me; I can imagine a situation with multiple connections and multiple temp emulation schemas. Keeping track at the connection level seems more obvious.

Changing lots of packages is harder...

**Comment by schuemie** [comment]
I'm ok with adding `tempEmulationSchema` to `connectionDetails` and `connection`. We could slowly deprecate the separate `tempEmulationSchema` argument in the HADES packages, encouraging people to use the one in DatabaseConnector instead.

I don't see a way to standardize CDM-specific parameters though. Most packages need `cdmDatabaseSchema` (but some don't), most need `cohortDatabaseSchema` and `cohortTable` (some need more cohort tables), a small number needs `resultsDatabaseSchema`, and unfortunately some need `vocabularyDatabaseSchema` (which I think is a mistake, since the vocab is part of the CDM).

**Comment by ablack3** [comment]
Ok great. My colleague @A1exanderAlexeyuk started working on this. I'll review his code and we'll make a PR that adds tempEmulationSchema to connection and connectionDetails. Then we'll find any functions in DatabaseConnector that use tempEmulationSchema and edit them so that they can use either the current approach or the new approach. We won't introduce any breaking changes but will allow tempEmulationSchema to be handled in connectionDetails and connection.

As for a CDM layer- we'll just let the idea ruminate since it is not important for tempEmulationSchema which will be at the database connection level.

**Comment by ablack3** [comment]
Should DatabaseConnector::connect() attempt to create tempEmulationSchema if it does not exist, or throw an error or a warning?

**Comment by schuemie** [comment]
Good question. In many scenarios you don't even use temp tables, so then it is ok if it doesn't exist. I also doubt there will be many users that have privileges to create schemas. So maybe do nothing, and let SqlRender throw the error when it needs it and it isn't there?

**Comment by ablack3** [comment]
That sounds good to me.

**Comment by A1exanderAlexeyuk** [comment]
@schuemie Do we need to drop tepmEmulationSchama (if it was created) in case of calling disconnect function?

**Comment by schuemie** [comment]
I'm going to go with the current implementation for now
