### ISSUE TITLE
BulkLoad Issue related to Invalid UTF8 characters

### ISSUE THREAD

**Issue by clairblacketer** [OHDSI/DatabaseConnector#166]
I am attempting to insert a subset of records from the CONCEPT table into Redshift, using the `bulkLoad = TRUE` option. I ran into an error and when I checked the stl_load_errors table it is because there is an unrecognized UTF8 character. In this case it is the Euro symbol. Would it be possible to add the [ACCEPTINVCHARS](https://docs.aws.amazon.com/redshift/latest/dg/copy-parameters-data-conversion.html#copy-acceptinvchars) option to redshiftCopy.sql to bypass this error?

**Comment by schuemie** [comment]
Sounds good. Could you create a pull request?

**Comment by clairblacketer** [comment]
Sure! I'm happy to put one together
