### ISSUE TITLE
Using DatabaseConnector to BigQuery doesn't work.

### ISSUE THREAD

**Issue by MichaelSchmidt82** [OHDSI/DatabaseConnector#169]
Hi,

I'm using Docker to build a data pipeline.  I downloaded and configured BigQuery's [JDBC](https://cloud.google.com/bigquery/docs/reference/odbc-jdbc-drivers#current_jdbc_driver) Simba driver; The driver responsible for gaining BQ access via DatabaseConnector.  I found the Simba [documentation](https://storage.googleapis.com/simba-bq-release/jdbc/Simba%20Google%20BigQuery%20JDBC%20Connector%20Install%20and%20Configuration%20Guide.pdf#page=1) helpful, and created `connectionString`'s as specified.  These strings were passed down to the `createConnectionDetails` function.

I tried all 4 auth types and was unable to connect to BigQuery.  Here are my results:

AuthType 0 -- Google Service Account (file confirmed to be accessible):
`connectionString <- "jdbc:bigquery://https://www.googleapis.com/bigquery/v2:443;ProjectId=redacted;OAuthType=0;OAuthServiceAcctEmail=redacted@redacted.iam.gserviceaccount.com;OAuthPvtKeyPath=/secrets/credentials.json;"`

Result:
```
Loading required package: DatabaseConnector
Connecting using BigQuery driver
Error in rJava::.jcall(jdbcDriver, "Ljava/sql/Connection;", "connect",  : 
  java.lang.ExceptionInInitializerError
Calls: connect ... connect -> connectUsingJdbcDriver -> <Anonymous> -> .jcheck
Execution halted
```

AuthType 1 -- Google User account (obviously this shouldn't work with docker):
`connectionString <- "jdbc:bigquery://https://www.googleapis.com/bigquery/v2:443;ProjectId=redacted;OAuthType=1"`

Result:
```
Loading required package: DatabaseConnector
Connecting using BigQuery driver
Error in rJava::.jcall(jdbcDriver, "Ljava/sql/Connection;", "connect",  : 
  java.sql.SQLException: [JDBC Driver]
No X11 DISPLAY variable was set, but this program performed an operation that requires it.
Calls: connect ... connect -> connectUsingJdbcDriver -> <Anonymous> -> .jcheck
Execution halted
```

AuthType 2 -- Using Pre-Generated Access and Refresh tokens:
`connectionString <- "jdbc:bigquery://https://www.googleapis.com/bigquery/v2:443;OAuthType=2;ProjectId=redacted;OAuthAccessToken=redacted;"

Result:
```
Loading required package: DatabaseConnector
Connecting using BigQuery driver
Error in rJava::.jcall(jdbcDriver, "Ljava/sql/Connection;", "connect",  : 
  java.lang.ExceptionInInitializerError
Calls: connect ... connect -> connectUsingJdbcDriver -> <Anonymous> -> .jcheck
Execution halted
```

AuthType 3 -- Using Application Default Credentials (env var set and confirmed)
`connectionString <- "jdbc:bigquery://https://www.googleapis.com/bigquery/v2:443;OAuthType=3;ProjectId=redacted"`

Result:
```
Loading required package: DatabaseConnector
Connecting using BigQuery driver
Error in rJava::.jcall(jdbcDriver, "Ljava/sql/Connection;", "connect",  : 
  java.lang.ExceptionInInitializerError
Calls: connect ... connect -> connectUsingJdbcDriver -> <Anonymous> -> .jcheck
Execution halted
```

Is there something I'm missing for BQ access using DatabaseConnector?

**Comment by MichaelSchmidt82** [comment]
The line in question is [here](https://github.com/OHDSI/DatabaseConnector/blob/b3d3162711aad954c3eb649751544c7a3d01455c/R/Connect.R#L608)

**Comment by schuemie** [comment]
I'm no expert in BigQuery. I am able to connect to a BQ instance using a connecting string that looks like this:

```
jdbc:bigquery://https://www.googleapis.com/bigquery/v2:443;ProjectId=redacted;OAuthType=0;OAuthServiceAcctEmail=ohdsi-service-account@redacted.iam.gserviceaccount.com;OAuthPvtKeyPath=redacted.json;Timeout=1000
```

**Comment by konstjar** [comment]
I see Docker is used. Do you install GCP SDK and authenticate inside Docker?

**Comment by MichaelSchmidt82** [comment]
> 

Thanks so much for this.  Definitely going this a try.

**Comment by MichaelSchmidt82** [comment]
My problem was 2-fold.  I had an issue with my java install, and I wasn't authenticated.

So next time I'll ask questions on the forum instead of raising an issue.

Thanks for the help.
