### ISSUE TITLE
Redshift issues

### ISSUE THREAD

**Issue by tshaddox** [OHDSI/DatabaseConnector#17]
Hi @anthonysena, @msuchard, and @schuemie, 

DatabaseConnector fails to connect to Redshift in IMEDS using a Windows instance for commit dcc97bd and later.  Commit 14332dd is the last commit that connects without error.  Here is the code that I ran.   Password redacted.

install.packages("devtools")
library(devtools)
install_github("ohdsi/SqlRender")
library(SqlRender)
install_github("ohdsi/DatabaseConnector", ref = "dcc97bd")

library(DatabaseConnector)
pw <- 
dbms <- "redshift"
user <- "demosymp"
server <- "omop-datasets.cqlmv7nlakap.us-east-1.redshift.amazonaws.com/truven"
cdmschemamdcr <- "mdcr_cdm4" 
port <- "5439"

connectiondetailsmdcr <- createConnectionDetails(dbms=dbms, server=server, user=user, password=pw, schema=cdmschemamdcr,port=port)
connmdcr <- connect(connectiondetailsmdcr)

The error is:
> connmdcr <- connect(connectiondetailsmdcr)
Connecting using Redshift driver
Error in .jfindClass(as.character(driverClass)[1]) : class not found

If there is more information I can give you to help solve this, please let me know.

Gratefully,
Trevor

**Comment by schuemie** [comment]
Hi Trevor,

I'm not able to reproduce the problem (using a 64-bit Windows instance in the lab), it works fine for me.
 
Could you tell me which Windows instance you're using? Also the 64-bit one?

Note that when jumping back and forth between versions of packages that rely on Java (like SqlRender and DatabaseConnector),  it is essential to terminate all R instances before installing a different version, because the JVM will stay loaded and keep all Java libraries locked.

Cheers,
Martijn

**Comment by tshaddox** [comment]
Hi Martijn,

I'm using a Windows 32 Ora/Redshift instance.  So, no, I'm using a 32 bit instance instead of a 64 bit one.  I actually can't see a 64 bit Windows option on my launch menu.   

I find that dcc97bd fails when installing from a fresh, untouched IMEDS instance.  So I imagine different R instances would not be a factor here?  Here is the full output below:

R version 3.1.1 (2014-07-10) -- "Sock it to Me"
Copyright (C) 2014 The R Foundation for Statistical Computing
Platform: i386-w64-mingw32/i386 (32-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

\> install.packages("devtools")
Warning in install.packages("devtools") :
  'lib = "C:/Program Files/R/R-3.1.1/library"' is not writable
--- Please select a CRAN mirror for use in this session ---
also installing the dependencies ‘mime’, ‘curl’, ‘openssl’, ‘R6’, ‘httr’, ‘memoise’, ‘whisker’, ‘digest’, ‘rstudioapi’, ‘jsonlite’, ‘git2r’, ‘withr’

trying URL 'http://lib.stat.cmu.edu/R/CRAN/bin/windows/contrib/3.1/mime_0.4.zip'
Content type 'application/zip' length 37255 bytes (36 Kb)
opened URL
downloaded 36 Kb

trying URL 'http://lib.stat.cmu.edu/R/CRAN/bin/windows/contrib/3.1/curl_0.9.5.zip'
Content type 'application/zip' length 4402831 bytes (4.2 Mb)
opened URL
downloaded 4.2 Mb

trying URL 'http://lib.stat.cmu.edu/R/CRAN/bin/windows/contrib/3.1/openssl_0.9.1.zip'
Content type 'application/zip' length 2718463 bytes (2.6 Mb)
opened URL
downloaded 2.6 Mb

trying URL 'http://lib.stat.cmu.edu/R/CRAN/bin/windows/contrib/3.1/R6_2.1.2.zip'
Content type 'application/zip' length 271117 bytes (264 Kb)
opened URL
downloaded 264 Kb

trying URL 'http://lib.stat.cmu.edu/R/CRAN/bin/windows/contrib/3.1/httr_1.1.0.zip'
Content type 'application/zip' length 253007 bytes (247 Kb)
opened URL
downloaded 247 Kb

trying URL 'http://lib.stat.cmu.edu/R/CRAN/bin/windows/contrib/3.1/memoise_1.0.0.zip'
Content type 'application/zip' length 22507 bytes (21 Kb)
opened URL
downloaded 21 Kb

trying URL 'http://lib.stat.cmu.edu/R/CRAN/bin/windows/contrib/3.1/whisker_0.3-2.zip'
Content type 'application/zip' length 64725 bytes (63 Kb)
opened URL
downloaded 63 Kb

trying URL 'http://lib.stat.cmu.edu/R/CRAN/bin/windows/contrib/3.1/digest_0.6.9.zip'
Content type 'application/zip' length 171586 bytes (167 Kb)
opened URL
downloaded 167 Kb

trying URL 'http://lib.stat.cmu.edu/R/CRAN/bin/windows/contrib/3.1/rstudioapi_0.5.zip'
Content type 'application/zip' length 46016 bytes (44 Kb)
opened URL
downloaded 44 Kb

trying URL 'http://lib.stat.cmu.edu/R/CRAN/bin/windows/contrib/3.1/jsonlite_0.9.19.zip'
Content type 'application/zip' length 1008615 bytes (984 Kb)
opened URL
downloaded 984 Kb

trying URL 'http://lib.stat.cmu.edu/R/CRAN/bin/windows/contrib/3.1/git2r_0.13.1.zip'
Content type 'application/zip' length 3071845 bytes (2.9 Mb)
opened URL
downloaded 2.9 Mb

trying URL 'http://lib.stat.cmu.edu/R/CRAN/bin/windows/contrib/3.1/withr_1.0.1.zip'
Content type 'application/zip' length 41457 bytes (40 Kb)
opened URL
downloaded 40 Kb

trying URL 'http://lib.stat.cmu.edu/R/CRAN/bin/windows/contrib/3.1/devtools_1.10.0.zip'
Content type 'application/zip' length 371632 bytes (362 Kb)
opened URL
downloaded 362 Kb

package ‘mime’ successfully unpacked and MD5 sums checked
package ‘curl’ successfully unpacked and MD5 sums checked
package ‘openssl’ successfully unpacked and MD5 sums checked
package ‘R6’ successfully unpacked and MD5 sums checked
package ‘httr’ successfully unpacked and MD5 sums checked
package ‘memoise’ successfully unpacked and MD5 sums checked
package ‘whisker’ successfully unpacked and MD5 sums checked
package ‘digest’ successfully unpacked and MD5 sums checked
package ‘rstudioapi’ successfully unpacked and MD5 sums checked
package ‘jsonlite’ successfully unpacked and MD5 sums checked
package ‘git2r’ successfully unpacked and MD5 sums checked
package ‘withr’ successfully unpacked and MD5 sums checked
package ‘devtools’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
        C:\Users\omop\AppData\Local\Temp\2\RtmpsP2mDP\downloaded_packages
\> library(devtools)
Warning message:
package ‘devtools’ was built under R version 3.1.3 
\> install_github("ohdsi/SqlRender")
Downloading GitHub repo ohdsi/SqlRender@master
from URL https://api.github.com/repos/ohdsi/SqlRender/zipball/master
Installing SqlRender
Installing 1 package: rJava
package ‘rJava’ successfully unpacked and MD5 sums checked
"C:/PROGRA~1/R/R-31~1.1/bin/i386/R" --no-site-file --no-environ --no-save  \
  --no-restore CMD INSTALL  \
  "C:/Users/omop/AppData/Local/Temp/2/RtmpsP2mDP/devtools668129e50d0/OHDSI-SqlRender-a5201d1"  \
  --library="C:/Users/omop/Documents/R/win-library/3.1" --install-tests 

\* installing *source* package 'SqlRender' ...
\** R
\** inst
\** tests
\** preparing package for lazy loading
\** help
\*** installing help indices
\** building package indices
\** installing vignettes
\** testing if installed package can be loaded
\* DONE (SqlRender)
\> library(SqlRender)
\> install_github("ohdsi/DatabaseConnector", ref = "dcc97bd")
Downloading GitHub repo ohdsi/DatabaseConnector@dcc97bd
from URL https://api.github.com/repos/ohdsi/DatabaseConnector/zipball/dcc97bd
Installing DatabaseConnector
Skipping 1 unavailable package: SqlRender
Installing 6 packages: bit, DBI, fastmatch, ff, ffbase, RJDBC
package ‘bit’ successfully unpacked and MD5 sums checked
package ‘DBI’ successfully unpacked and MD5 sums checked
package ‘fastmatch’ successfully unpacked and MD5 sums checked
package ‘ff’ successfully unpacked and MD5 sums checked
package ‘ffbase’ successfully unpacked and MD5 sums checked
package ‘RJDBC’ successfully unpacked and MD5 sums checked
"C:/PROGRA~1/R/R-31~1.1/bin/i386/R" --no-site-file --no-environ --no-save  \
  --no-restore CMD INSTALL  \
  "C:/Users/omop/AppData/Local/Temp/2/RtmpsP2mDP/devtools668dae2766/OHDSI-DatabaseConnector-dcc97bd"  \
  --library="C:/Users/omop/Documents/R/win-library/3.1" --install-tests 

\* installing *source* package 'DatabaseConnector' ...
\** R
\** inst
\** tests
\** preparing package for lazy loading
Warning: package 'RJDBC' was built under R version 3.1.3
Warning: package 'DBI' was built under R version 3.1.3
Warning: package 'rJava' was built under R version 3.1.3
\** help
\*** installing help indices
\** building package indices
\** testing if installed package can be loaded
Warning: package 'RJDBC' was built under R version 3.1.3
Warning: package 'DBI' was built under R version 3.1.3
Warning: package 'rJava' was built under R version 3.1.3
\* DONE (DatabaseConnector)
\> 
\> library(DatabaseConnector)
Loading required package: RJDBC
Loading required package: DBI
Loading required package: rJava
Warning messages:
1: package ‘RJDBC’ was built under R version 3.1.3 
2: package ‘DBI’ was built under R version 3.1.3 
3: package ‘rJava’ was built under R version 3.1.3 
\> pw <- 
\> dbms <- "redshift"
\> user <- "demosymp"
\> server <- "omop-datasets.cqlmv7nlakap.us-east-1.redshift.amazonaws.com/truven"
\> cdmschemamdcr <- "mdcr_cdm4" 
\> port <- "5439"
\> 
\> connectiondetailsmdcr <- createConnectionDetails(dbms=dbms, server=server, user=user, password=pw, schema=cdmschemamdcr,port=port)
\> connmdcr <- connect(connectiondetailsmdcr)
Connecting using Redshift driver
Error in .jfindClass(as.character(driverClass)[1]) : class not found
\> 
\> 
\> 

Take care,
Trevor

**Comment by schuemie** [comment]
Hi Trevor,

Sorry about that. The RedShift driver was incompatible with the Java version running in the lab (32-bit environment). I changed the driver version. If you install the latest version of DatabaseConnector, all should be good now.

Cheers,
Martijn

**Comment by tshaddox** [comment]
Hi Martijn,

Yep, that fixed it.  Thank you!

Take care,
Trevor

**Comment by anthonysena** [comment]
Sorry about that @tshaddox! Thanks for the fix @schuemie - I'll keep that in mind for any future changes.
