### ISSUE TITLE
Hive not listed in supported dbms despite being implemented

### ISSUE THREAD

**Issue by drowlingua** [OHDSI/DatabaseConnector#172]
In [R/Connect.R](https://github.com/OHDSI/DatabaseConnector/blob/b3d3162711aad954c3eb649751544c7a3d01455c/R/Connect.R), hive is not listed in [supported dbms](https://github.com/OHDSI/DatabaseConnector/blob/b3d3162711aad954c3eb649751544c7a3d01455c/R/Connect.R#L19) despite being implemented in `connect` on line [511](https://github.com/OHDSI/DatabaseConnector/blob/b3d3162711aad954c3eb649751544c7a3d01455c/R/Connect.R#L511). This makes it unusable since this supported dbms list is checked before connection is made.

**Comment by schuemie** [comment]
Sorry about that. I've now [fixed it](https://github.com/OHDSI/DatabaseConnector/commit/3bdca856933f6b58fdc3399e6ba1839e801465f4) in the develop branch. 

I'm not sure how long we'll continue to support Hive. The last code for Hive was submitted 3 years ago, and we don't even have a testing server. Please use at your own risk.

**Comment by drowlingua** [comment]
Cool thank you
