### ISSUE TITLE
extending connectionDetails

### ISSUE THREAD

**Issue by vojtechhuser** [OHDSI/DatabaseConnector#18]
I like the idea of connectionDetails to house common parameters.
I suggest we extend this object with few more attributes.

cdmDatabaseSchema
oracleTempSchema = cdmDatabaseSchema,
cdmVersion = 5
resultSchema = 'results'

this would reduce number of parameters passed back and forth and standardize the naming for future studies.

**Comment by schuemie** [comment]
Even though the DatabaseConnector is often used in methods working on the CDM, it is not restricted to those use cases. For example, people use DatabaseConnector to connect to the LAERTES database instead. In those cases, the proposed extra parameters would not make sense.

Sorry, not going to add these!
