### ISSUE TITLE
getTableNames does not seem to work on BigQuery

### ISSUE THREAD

**Issue by ablack3** [OHDSI/DatabaseConnector#182]
Unfortunately I don't have a reproducible example using public bigquery data.

After I create my bigquery connection
`DatabaseConnector::getTableNames(con, cdmDatabaseSchema)` returns an empty character vector.

I stepped through the key parts of the function and don't see any obvious error. This may be a JDBC driver issue.

```
metaData <- rJava::.jcall(con@jConnection, "Ljava/sql/DatabaseMetaData;", "getMetaData")
types <- rJava::.jarray(c("TABLE", "VIEW"))
resultSet <- rJava::.jcall(metaData,
                           "Ljava/sql/ResultSet;",
                           "getTables",
                           database,
                           schema,
                           rJava::.jnull("java/lang/String"),
                           types,
                           check = FALSE)

tables <- character()
while (rJava::.jcall(resultSet, "Z", "next")) {
  tables <- c(tables, rJava::.jcall(resultSet, "S", "getString", "TABLE_NAME"))
}
tables
#> character(0)
```

This is causing CohortDiagnostics to fail on BigQuery [here](https://github.com/OHDSI/CohortDiagnostics/blob/3836704a674e68964dfa6ef13f8777bcea60780d/R/ConceptIds.R#L94).

Interestingly when I use the [bigrquery](https://bigrquery.r-dbi.org/) package to connect the dbListTables function works as expected. Unfortunately I can't use at this connection to run CohortDiagnostics though.

```
library(DBI)

con <- dbConnect(
  bigrquery::bigquery(),
  project = "Project",
  dataset = "someDataset",
  billing = "Project"
)

dbListTables(con)
#> [1] "attribute_definition"  "care_site"             "cdm_source"            "cohort" ...
```

@mdlavallee92

**Comment by ablack3** [comment]
I'm not easily finding official documentation on the jdbc methods. 

This is from [Microsoft](https://docs.microsoft.com/en-us/sql/connect/jdbc/reference/gettables-method-sqlserverdatabasemetadata?view=sql-server-ver15):
public java.sql.ResultSet getTables(java.lang.String catalog,  
                                    java.lang.String schema,  
                                    java.lang.String table,  
                                    java.lang.String[] types)

I tried many variations of passing in different values for arguments including nulls. Nothing seemed to work as expected.

**Comment by schuemie** [comment]
I've seen this issue before (although I can't find any record of this), and I think I remember the conclusion was missing privileges for your BQ account.

Using my account (provided by Odyssseus) I can use getTableNames just fine, as tested [here](https://github.com/OHDSI/DatabaseConnector/blob/main/extras/TestOtherPlatforms.R#L140).

**Comment by schuemie** [comment]
Ah, here's the [prior issue](https://github.com/ohdsi-studies/MusculoskeletalAEsAfterAIs/issues/5).

**Comment by ablack3** [comment]
Thanks for the info! It's strange because I think I have all permissions a normal user would have.

**Comment by jdposada** [comment]
hi @ablack3 ,

This is a scope issue. When your scope of access is limited thourgh a service acccount then the function works. But if you have a wide access, as the one you may have as a user then the function fails. I remember this function trying to get table names from all the datasets I have access. Defintely a JDBC driver issue, since the scope cannot be limited by any of the available configurations.

**Comment by ablack3** [comment]
This was indeed a permission issue. Thanks for the help!

**Comment by jdposada** [comment]
hi @ablack3 @schuemie ,

Maybe creating an issue to update the docs and reflect the need for a limited scope of access?

**Comment by ablack3** [comment]
I'm not sure the exact permission that was missing. I was able to get the table and view names from one schema (aka dataset) in bigquery using my personal credentials.
