### ISSUE TITLE
Create Fatal Error when load package in RStudio 2022.02.2

### ISSUE THREAD

**Issue by MimiYuchenGuo** [OHDSI/DatabaseConnector#183]
When updating R to the latest 4.2.0, it still can be loaded in R GUI vanilla one. But if using updated RStudio 2022.02.2, every time I loaded DatabaseConnector, the session was aborted with a fatal error. 

I tried with RStudio 2021.09.2, it was giving me the same fatal error crash. 

I solved it by downgraded Rstudio to 2021.09.1 which I will need a lower version of R (4.1.3), there is no error. (Or just use vanilla R whichever version).

**Comment by schuemie** [comment]
I've created [an issue with RStudio](https://github.com/rstudio/rstudio/issues/11159). They may blame rJava though.

**Comment by MimiYuchenGuo** [comment]
Thanks a lot for your reply. I see the problem now, I haven't got to rjava before it crashed, was just trying Eunomia from OHDSI and it crashed when loading DatabaseConnecter so I thought that's the problem. Many thanks for spending time trying this weird combination. I'll follow up on the RStudio issue.

**Comment by schuemie** [comment]
Thanks @MimiYuchenGuo, for alerting us to this issue! As you can see, the issue can be resolved by installing the patched version of R. Hopefully R 4.2.1 will be released soon, including this patch.
