### ISSUE TITLE
supporting Google BigQuery

### ISSUE THREAD

**Issue by hajarhomayouni** [OHDSI/DatabaseConnector#19]
Hi,
Does DatabaseConnector support Google BigQuery? If not, which files should I change to add this feature?
Any idea would be really appreciated.

**Comment by schuemie** [comment]
Hi Hajar,

See my [post on the forums](http://forums.ohdsi.org/t/supporting-dbms-platforms-other-than-sql-server-postgresql-oracle-and-redshift/138/14). I'm afraid it will not be that easy because there does not appear to be a (viable) JDBC driver for Google BigQuery.
