### ISSUE TITLE
function for insert and other queries

### ISSUE THREAD

**Issue by hajarhomayouni** [OHDSI/DatabaseConnector#20]
in the example to test DatabaseConnector, you used querySql to execute a select query:

**querySql(conn,"SELECT COUNT(*) FROM person")**

What do you use for insert and other queries?

Thank you

**Comment by schuemie** [comment]
`querySql` should be used when a SQL statement will return a result (which can be an empty data set). You can only have 1 statement in the SQL.

`executeSql` should be used for all other SQL statements, including updates, inserts, deletions, drops, etc. You can have multiple SQL statements in the same SQL string, but don't forget to terminate each statement with a semicolon.

**Comment by vojtechhuser** [comment]
insertTable()
