### ISSUE TITLE
5.1.0 breaks backwards compatibility on sql server - deviates from typical drop table 

### ISSUE THREAD

**Issue by rtmill** [OHDSI/DatabaseConnector#204]
https://github.com/OHDSI/DatabaseConnector/blob/6bdece864cfa9a5c9ea9b6d5473df4d2f8a30335/R/InsertTable.R#L276

https://github.com/OHDSI/DatabaseConnector/blob/main/R/InsertTable.R
Line 276
"sql <- "DROP TABLE IF EXISTS @tableName;""

See above. Not sure of advantages of switching to "IF TABLE NOT EXISTS" vs. the working standard (i.e. "IF OBJECT_ID('...', 'U') IS NOT NULL") but it causes heaps of headaches. Had to revert to v5.0.6 to run CohortDiagnostics for symposium.

**Comment by azimov** [comment]
Related to [SqlRender issue](https://github.com/OHDSI/SqlRender/issues/306) for older versions of SqlServer

**Comment by schuemie** [comment]
'causes heaps of headaches'. How many sites are we talking about?

**Comment by schuemie** [comment]
Please upgrade your SQL Server.
