### ISSUE TITLE
DLL Authentication Not Working

### ISSUE THREAD

**Issue by sarahgbmc** [OHDSI/DatabaseConnector#207]
Starting today, I have been unable to connect to my OMOP database (SQL Server). My connection has worked well for several months, so I'm trying to figure out why I am getting this error when I try to connect. The only thing that has changed with my environment is that my user now has admin permissions - the login information is the same.

I have my PATH_TO_AUTH_DLL set to the folder where the files live:
![image](https://user-images.githubusercontent.com/103575490/199598370-c2dbdb44-978b-4dec-8aeb-433bc24d759e.png)

`
Sys.setenv("PATH_TO_AUTH_DLL" = "C:/Temp/jdbcDrivers")`
`Sys.setenv("DATABASECONNECTOR_JAR_FOLDER" = "C:/Temp/jdbcDrivers") 
`
But when I run my code to connect (replacing "myserver" with the name of my server), I get the error below.
`connectionDetails <- createConnectionDetails(dbms = "sql server",
                                             server = "myserver")`
`connection <- connect(connectionDetails)`

**Error in .jcall("RJavaTools", "Ljava/lang/Object;", "invokeMethod", cl,  : 
  java.io.IOException: Failed to get field handle to set library path**

I have tried running R as an administrator (no difference), copying the files to C:/Windows/System32 (also no difference).

Do I need to download a new version of the DLL files? Do something differently now that my user has admin rights?

Thank you!

**Comment by schuemie** [comment]
So the error originates [here](https://github.com/OHDSI/DatabaseConnector/blob/main/java/org/ohdsi/databaseConnector/Authentication.java#L30), when we try to add the DLL to the Java path at runtime. This uses a rather low-level Java function, and Java says it doesn't exist. Could it be that your Java version has changed?

If you have admin rights, and can add DLLs to System32, we don't actually need to add the DLL at runtime. Could you try unsetting the PATH_TO_AUTH_DLL variable using 

```r
Sys.unsetenv("PATH_TO_AUTH_DLL")
```

make sure the DLL is in System32, and try again?

**Comment by sarahgbmc** [comment]
That was a very easy fix! Unsetting the PATH_TO_AUTH_DLL solved the issue.

Thanks so much!
