### ISSUE TITLE
Support for External Tables in getTableNames 

### ISSUE THREAD

**Issue by alondhe** [OHDSI/DatabaseConnector#210]
We have a Redshift instance that uses external CDM tables. In SqlWorkbenchJ, they appear as "EXTERNAL TABLES" rather than "TABLES," so it seems that the JDBC connection delineates between these two types, even though queries / commands act as if they are regular tables. 

In DatabaseConnector, when issuing the connection, the external tables do not appear in the RStudio Connections GUI, as the getTableNames function (via the Java call to getTables) does not look for them. 

Low priority, but perhaps we can expand the function call to grab external tables -- and maybe as an optional argument in the connectionDetails.

**Comment by schuemie** [comment]
Sounds reasonable. Would you happen to know how to list the external tables through JDBC?

**Comment by alondhe** [comment]
Not yet, still brushing up on the java function call.

**Comment by schuemie** [comment]
Now added to the `beta_6.0.0` branch. Could you give it a try?

**Comment by rfherrerac** [comment]
Hi, I just installed it and it works. Thanks a lot.

**Comment by schuemie** [comment]
Thanks for checking! This will be included in the next release, probably in the first weeks of 2023
