### ISSUE TITLE
Update Spark drivers to work with Databricks

### ISSUE THREAD

**Issue by lcpinheiro** [OHDSI/DatabaseConnector#211]
Database connector allows a spark connection via a Simba Spark JDBC driver. While connection is made, it is unstable, causing multiple "Metadata initialisation error" and more importantly throwing errors in multiple SQL changes e.g. in Achilles export's SQLs at least three SQLs could not run. 

These errors do not occur when the SQL codes are run in Databricks' own cloud SQL notebook, which seems to confirm this is in fact a driver issue.

Subsequently, I've tested using Databricks own Spark driver (https://www.databricks.com/spark/jdbc-drivers-download) and sparklyr to query the same SQLs that did not work using the Simba Spark driver. They all worked with the Databricks spark driver. In addition, the "Metadata initialisation error" goes away.

Could you please update DatabaseConnector to allow the use the Databricks own JDBC driver for Databricks spark SQL databases?

**Comment by schuemie** [comment]
@alondhe: Could you help us understand the choice for the Simba Spark driver? 

I think this might also be a good use case for the approach discussed in #185, where instead of using the jdbc driver we wrap the sparklyr DBI driver in DatabaseConnector.

**Comment by alondhe** [comment]
Originally (around Q3 2021), before Databricks posted drivers, we used the Simba Spark driver. But sometime early this year, we then changed the approach to use the newly available Databricks JDBC driver in our site's local repos. I'm trying to track this code down; or at least recreate it.

sparklyR could be interesting, but I'm not knowledgeable about it.

**Comment by schuemie** [comment]
From what I understand from @leeevans , our current testing server implements Apache Spark, but is not a Databricks server. Unfortunately, the Databricks JDBC driver appears to require Databricks (you have to provide a 'compute resources URL' for it to work). 

The `sparklyr` package should work, but I get this error:
```
cannot open file 'C:\Users\ADMIN_~3\AppData\Local\Temp\2\RtmpMtcz2I\file2460119258d3_spark.log': Permission denied
```
Some googling suggests this is a common error that **has nothing to do with write access**, but may indicate any of a large number of problems. Anyone have any experience with setting up sparklyr on Windows?

**Comment by lcpinheiro** [comment]
Hi @schuemie, for sparklyr, I followed the steps in https://spark.rstudio.com/deployment/databricks-cluster-remote.html. This is not the easiest set up as you need to create a python venv and configure the connection. 

Might this link - https://docs.databricks.com/integrations/jdbc-odbc-bi.html - help devise a simpler approach to connection that can integrate with DatabaseConnector?

I'm happy to test on our Databricks instance, but am no expert in JDBC/ODBC connections unfortunately.

**Comment by schuemie** [comment]
Thanks @lcpinheiro . As mentioned, we don't have a Databricks testing environment anymore, just a Spark server. I'm unable to configure sparklyr to connect to that.

As you can see [here](https://docs.databricks.com/integrations/jdbc-odbc-bi.html#building-the-connection-url-for-the-databricks-driver), the JDBC driver requires a `Http Path` parameter, which is specific to Databricks.

**Comment by alondhe** [comment]
Hi @schuemie -- regarding the Databricks testing env. Last I heard from them and in discussing with @leeevans: they could provide it, but to reduce cost, it would need to auto-shutdown after an inactive period, but then we could use Databricks API calls in GitHub actions (or as a manual step) to spin it back up. Was this idea not feasible?

**Comment by alondhe** [comment]
And I agree with @lcpinheiro that the Databricks JDBC driver doesn't have all the errors mentioned above. We ran Achilles successfully for dozens of CDM loads this year at my previous company.

**Comment by leeevans** [comment]
It wasn't feasible to implement a custom solution to work around the Databricks sleep mode and running it 'always on' would have incurred an unacceptable cost in OHDSI cloud AWS resources.

Instead I put in place a single node spark-SQL OHDSI testing server so we can support Spark-SQL. That OHDSI test database can be used to verify that SqlRender/Database connector is generating valid spark-SQL (Databricks uses the spark-SQL dialect).

The reality is that OHDSI support specifically for the Databricks DBMS, would require the OHDSI HADES team to have access to a remote Databricks instance hosted by Databricks, or by a member of the OHDSI community that is actively using Databricks, in an 'always on' mode.

**Comment by lcpinheiro** [comment]
Thanks all, so what I'm hearing is that we need to patch the DatabaseConnector package locally (it seemed to have worked for @alondhe ) and that in the current set up, the community cannot support DatabaseConnector for Databricks, is that a fair reflection? 

If so, I'll get back to our Databricks rep and see what can be done locally.

**Comment by alondhe** [comment]
@schuemie and @leeevans - understood. I'm going to connect with my colleagues and Databricks to see if there's any path forward with an always-on cluster.

**Comment by schuemie** [comment]
I think I found the [sparklyr issue](https://github.com/sparklyr/sparklyr/issues/2472) corresponding to my current problem. The bad news it is already open for over two years, so not expecting it to be solved anytime soon.

**Comment by lcpinheiro** [comment]
Hi @schuemie, @alondhe, @leeevans. We got word from Databricks and there's an initial suggestion of using https://github.com/zacdav-db/brickster. I'll give it a try, but wonder if anyone has already tried this?

**Comment by dmoore247** [comment]
brickster is good from what I hear for Native R programmers.

For SQL users and SQL based tools...
Databricks [Serverless SQL](https://docs.databricks.com/serverless-compute/index.html) would address timeout issues experienced with Classic SQL Warehouses and clusters and also turn off quickly after the Serverless SQL Warehouse becomes idle.
Definitely use Databricks ODBC drivers with R based SQL interfaces over any generic Spark SQL drivers.

Please connect on LinkedIn and we'll help you out on this.

**Comment by schuemie** [comment]
I really don't see a path forward unless we get a DataBricks testing server. I'm trying to talk to folks at DataBricks, but no luck so far. We need a server that is always on (can be a tiny one), and since we're only using the server to ensure our free software runs for DataBricks customers, it seems silly we'd have to pay lots of money for that.

**Comment by edurdevic** [comment]
@schuemie if you can get a Databricks testing server with auto-termination, I can help you to modify the test pipeline to start the cluster at the beginning of the Github actions pipeline.
We can use [Databrciks CLI to start a cluster](https://docs.databricks.com/dev-tools/cli/clusters-cli.html#start-a-cluster) and at a later stage wait until the [status of the cluster](https://docs.databricks.com/dev-tools/cli/clusters-cli.html#get-information-about-a-cluster) is "RUNNING".

**Comment by mrechkem** [comment]
@schuemie - After speaking with my organization, we can supply a DataBricks environment for the community to conduct their testing. We'll likely have the cluster up and running sometime next week for your use, so please let me know if you have any specific requests so that we can ensure that you have everything you may need. Also, I'll be organizing a Spark/DataBricks workgroup if anyone is interested joining to continue supporting the community with this dialect.

**Comment by PRijnbeek** [comment]
@mrechkem that is great could you add me to the Workgroup we will add a person from my team. Where will the information about these workgroups be shared @schuemie in the Forum I assume in Developers channel?

**Comment by schuemie** [comment]
@mrechkem: That sounds great! Thank you for taking the lead on this!

**Comment by mrechkem** [comment]
@schuemie - You're very welcome. @PRijnbeek- Great, I'm in discussion with Databricks to make sure we have everything setup correctly, so I'll be in touch about the workgroup idea after the difficult part is finished.

**Comment by konstjar** [comment]
@schuemie @leeevans I do not know if it fits your needs, but as I understand as OHDSI community, we can apply to get free community edition instance
https://docs.databricks.com/getting-started/community-edition.html

**Comment by PRijnbeek** [comment]
@mrechkem great keep me in the loop.

**Comment by mrechkem** [comment]
@PRijnbeek -Sure, I just invited you to the Databricks environment via email, so let me know if you were able to access it fine.

**Comment by gongliangz** [comment]
@schuemie Hi Dr. Schuemie, we can not run PLE R package in Databricks environment using SparkJDBC driver. Can you add DatabricksJDBC (https://www.databricks.com/spark/jdbc-drivers-download) to the Databaseconnector package you developed? so we can test it. Thanks!

**Comment by schuemie** [comment]
@gongliangz : I tried the DataBricks JDBC driver. When trying to connect to our DataBricks testing server, it throws an error without error message. Any suggestions?

**Comment by schuemie** [comment]
Nevermind, I figured it out (URL now has to start with 'jdbc:databricks:' instead of 'jdbc:spark:')

I see the autocommit issue also exists with this driver version. I've reported this issue (which is described in the [OHDSI Databricks user group channel](https://teams.microsoft.com/l/channel/19%3a54e0717f78fb428ea842ca1d5fec53dc%40thread.tacv2/Databricks%2520Users%2520Group?groupId=3c4549e9-9de8-4827-9813-e751120326ad&tenantId=a30f0094-9120-4aab-ba4c-e5509023b2d5)) to Databricks a few months ago, but haven't had a (meaningful) response yet.

I've spent an insane amount of time on Databricks already. There will be no more work in HADES until the autocommit issue is resolved. Please gently remind your Databrick representative.

**Comment by gongliangz** [comment]
@schuemie Thank you so much! I have reported the autocommit issue to my leader.

**Comment by schuemie** [comment]
Note that the error remains when using `IgnoreTransactions=1`

**Comment by gongliangz** [comment]
@schuemie Hi Dr. Schuemie, We received a comment from Databricks team. 
----I am asking internally, hence asking have you tried connection.setAutoCommit(false) ?
Is it useful? thanks

**Comment by schuemie** [comment]
The Spark drivers have now been updated to the latest (DataBricks) version. All issues appear to have been resolved

**Comment by gongliangz** [comment]
Hi Dr. Schuemie,
Thank you for your information. Can you give me a template of setting parameters in Databaseconnector?, Thanks

**Comment by schuemie** [comment]
My code for connecting looks something like this:
```r
library(DatabaseConnector)
connectionDetails <- createConnectionDetails(
  dbms = "spark",
  connectionString = "jdbc:databricks://my-org.cloud.databricks.com:443/default;transportMode=http;ssl=1;AuthMech=3;httpPath=/sql/1.0/warehouses/1234abcde1234;",
  user = "joe@my.org.com",
  password = "abcdefghijklmnopqrstuvwxyz"
)
connection <- connect(connectionDetails)
disconnect(connection)
```

**Comment by TomWhite-MedStar** [comment]
@schuemie , thanks for making that change.  I tested the new databricks driver for CohortDiagnostics (using the IgnoreTransactions=1 option) and I no longer get the autocommit error.
