### ISSUE TITLE
Throw informative warning if user sets secure connection details to something that can't be resolved in another thread

### ISSUE THREAD

**Issue by schuemie** [OHDSI/DatabaseConnector#214]
Right now, something like this

```R
server <- "db.server.com"
connectionDetails <- createConnectionDetails(server = server, …)

execute(connectionDetails = connectionDetails, …)
```
will throw an error like 
```
object 'server' not found
```
when the connection details are passed to different threads. This is because the connection details don't store sensitive information (like the server name), instead keeping a reference, and the referenced server variable doesn't exist in the separate threads.

I think it is fine that this doesn't work (having your credentials in your code is not a good idea), but it would be good to warn the user already when creating the connection details.

**Comment by schuemie** [comment]
Fixed in https://github.com/OHDSI/DatabaseConnector/commit/0451de193cd5ea481bf862cd7972dffb6fbc5264

**Comment by azimov** [comment]
In unit tests we still use strings and this warning can get in the way, and there are situations where keyring doesn't make sense (e.g. sqlite paths). I added the PR #216 to suppress this warning in these situations
