### ISSUE TITLE
Snowflake and case sensitivity

### ISSUE THREAD

**Issue by DrTTrousers** [OHDSI/DatabaseConnector#217]
https://github.com/OHDSI/DatabaseConnector/blob/3144d21e0280b8e0d46c50b18b12aa01ad9fa9ce/R/ListTables.R#L45

Hi all

Snowflake is case sensitive in its requests for tables and schema's etc. This can be partially compensated for by setting variables for table/schema names as upper case, I have encountered new troubles further along the pipeline of an ongoing project (inside cohortDiagnostics) 

I think what is happening is during the programme, variables are generated and being passed from .csv files or the such as lower case, being entered into the snowflake database becoming upper case, and thus returning null from the database when queried again.

I have referenced line 45 in the list tables function by way of example, could this function and any other similar other occasions be ammended for snowflake compatibility by including:

` if (dbms(connection) == "snowflake") {
      databaseSchema <- toupper(databaseSchema)`

Edit for context: CohortDiagnostics bombs out after identifying orphan concepts on one of the makeassert calls checking if something is a character, I _think_ its these ones: https://github.com/OHDSI/CohortDiagnostics/blob/1837d18f114f9fb1da02d9b2a705b6cbb35319d9/R/RunDiagnostics.R#L201
but I'm still digging. For now I will need to switch dbms.

**Comment by schuemie** [comment]
Thanks! I've tried fix this [here](https://github.com/OHDSI/DatabaseConnector/commit/2e0f059ef2d9c229e5973ef3178204e1d02ca62f). It is currently in the develop branch. We're about to release DatabaseConnector v6.0.0, and it will be included there (including a ton of other changes).

Note: I don't have access to a Snowflake testing server, so can't guarantee this works.
