### ISSUE TITLE
Beta 6.0.0 error when using createMergedResultsFile

### ISSUE THREAD

**Issue by alondhe** [OHDSI/DatabaseConnector#219]
Hi @schuemie ,

We're using the new beta_6.0.0 so that getTableNames() can see our Redshift external tables, which is working great. However, when using CohortDiagnostics' createMergedResultsFile() function, we're seeing the below error, which wasn't in 5.1.0: 

```
Error in initialize(...) : 
  Assertion on 'connectionDetails' failed: Must inherit from class 'connectionDetails', but has classes 'ConnectionDetails','DefaultConnectionDetails'.
```

Has the class name changed?

Thanks,
Ajit

**Comment by schuemie** [comment]
(v6.0.0 has been released, so please use that, not the branch)

Yes, the class name has changed. I ran reverse dependency checks on all HADES packages, but I guess this wasn't unit tested. Please open an issue with CohortDiagnostics

**Comment by YeechingTiger** [comment]
Same error here when using DataQualityDashboard v2.0.0. We have to use 5.1.0 to make it run.

**Comment by alondhe** [comment]
Thanks @schuemie, will shift to the v6 release and raise the issue in CohortDiagnostics.
