### ISSUE TITLE
MS SQL - integrated security login problems

### ISSUE THREAD

**Issue by vojtechhuser** [OHDSI/DatabaseConnector#22]
I studied the documentation here but I am not able to use MSSQL integrated security (or other login)
https://raw.githubusercontent.com/OHDSI/DatabaseConnector/master/extras/DatabaseConnector.pdf

I would like to find out out from other MS SQL users, how they connect to the server using the R DatabaseConnect package

I prefer integrated security (win login) but any working solution will do.  (I am worried however that only integrated security will let me connect).   I am a user on a domain. 

This are options I tried with no luck with any of them.
```R 
#windows auth
connD <- createConnectionDetails(dbms="sql server",user=myUser, server=myServer,schema=mySchema)
#windows auth with domain
connD <- createConnectionDetails(dbms="sql server",user=myUser, server=myServer,domain=myDomain,schema=mySchema)
#not using integrated security - plain username and psw
connD <- createConnectionDetails(dbms="sql server",user=myUser, password = myPsw,server=myServer,domain=myDomain,schema=mySchema)
```

Can you please advise what are working connectionDetails approaches that are working fine at other sites

Errors I am getting.

```
> conn<-connect(connD)
Connecting using SQL Server driver
Warning: Using JTDS driver because a domain is specified. This may lead to problems. Try using integrated security instead.
Error in .jcall(drv@jdrv, "Ljava/sql/Connection;", "connect", as.character(url)[1],  : 
  java.sql.SQLException: Login failed. The login is from an untrusted domain and cannot be used with Windows authentication.


Connecting using SQL Server driver
Error in .jcall(drv@jdrv, "Ljava/sql/Connection;", "connect", as.character(url)[1],  : 
  com.microsoft.sqlserver.jdbc.SQLServerException: Login failed for user 'vhuser'. ClientConnectionId:a5652c6f-378a-47a4-ae38-c07b3f296566
> 

```

**Comment by schuemie** [comment]
Have you tried using integrated security?

> To be able to use Windows authentication for SQL Server, you have to install the JDBC driver. Download the .exe from [Microsoft](http://www.microsoft.com/en-us/download/details.aspx?displaylang=en&id=11774) and run it, thereby extracting its contents to a folder. In the extracted folder you will find the file sqljdbc_4.0/enu/auth/x64/sqljdbc_auth.dll (64-bits) or sqljdbc_4.0/enu/auth/x86/sqljdbc_auth.dll (32-bits), which needs to be moved to location on the system path, for example to c:/windows/system32.

Alternatively, you may need to specify the user running R-Studio, as described in the [documention](https://github.com/OHDSI/DatabaseConnector/blob/master/man-roxygen/DbmsDetails.R#L125).

**Comment by vojtechhuser** [comment]
Thanks. I missed that part of the documentation. The first advice (auth.dll) did the trick.
