### ISSUE TITLE
DatabaseConnector - connectionDetails must be an object of class 'connectionDetails'

### ISSUE THREAD

**Issue by ljubojevicvanja** [OHDSI/DatabaseConnector#220]
Hello everyone, I've run into this error (**connectionDetails must be an object of class 'connectionDetails'**) after the last update of DatabaseConnector (v6.0.0). I was trying to run DQD checks, and after DataQualityDashboard::executeDqChecks, this error occurred.
DQD was working just fine with DatabaseConnector v5.1.0 few days ago, so I assumed that the problem could be with the version of DatabaseConnector. I did some research and would like to share what I've found:

**DatabaseConnector v6.0.0**
- after executing DatabaseConnector::createConnectionDetails, connectionDetails is object of class:  attr(,"class") [1] "ConnectionDetails" "DefaultConnectionDetails", and for input check in executeDqChecks.R (https://github.com/OHDSI/DataQualityDashboard/blob/6c9c8fedb5a545dda6c34112acef40decda1fc5e/R/executeDqChecks.R#L79), condition  "_if (!("connectionDetails" %in% class(connectionDetails)))_" is checking for objects of class "connectionDetails", and it does not exist. 

**DatabaseConnector v5.1.0**
- after executing DatabaseConnector::createConnectionDetails, connectionDetails is object of class:  attr(,"class") : [1] "connectionDetails", so there is no problem with input check in executeDqChecks.R.

So, I revert DatabaseConnector to its previous version 5.1.0 and the DQD is now running.

**Comment by schuemie** [comment]
Yes, all packages depending on DatabaseConnector should update to the new class name. Sorry.
