### ISSUE TITLE
`DatabaseConnector::dbListTables()` broken against `snowflake` dbms

### ISSUE THREAD

**Issue by msuchard** [OHDSI/DatabaseConnector#221]
The function `DatabaseConnector::dbListTables()` appears to wrongly return (reported by a data partner) `character(0)` when executed against a `snowflake` dbms.  

To my friends developing for the `snowflake` dbms, please:
1. confirm this behavior
2. patch the issue, and
3. provide access to a `snowflake` server to HADES developers ASAP for (1) CI testing and (2) development.

**Comment by konstjar** [comment]
@msuchard thanks for reporting, we will investigate and provide solution.

**Comment by msuchard** [comment]
Thanks, @konstjar !

Interestingly, the data partner user reported this trouble with `DatabaseConnector` v5.1.0.   I just tried using v6.0.0 and `DatabaseConnector::dbListTables()` appears to work in my hands.

Was this possibly fixed between v5.1.0 and v6.0.0 ?

**Comment by konstjar** [comment]
@msuchard I checked both v5.1.0 and v6.0.0 - all of them work correct and produce the same results.
Could you please ask data partner to share sessionInfo state and what version of Snowflake driver is used? The tested and confirmed is Snowflake JDBC V3.13.22. It's possible to get it by running `DatabaseConnector::downloadJdbcDrivers("snowflake")` command.
