### ISSUE TITLE
Losing 3 hours in timestamps on Snowflake 

### ISSUE THREAD

**Issue by schuemie** [OHDSI/DatabaseConnector#223]
When inserting datetime type data into Snowflake and retrieving it back, we appear to lose 3 hours. Code to reproduce this is below. You can also see the SQL type is `TIMESTAMPNTZ`, so without time zone (so that shouldn't cause this issue). My guess this is a JDBC issue. 

```r
connection <- connect(connectionDetails)
data <- data.frame(dt = as.POSIXct("2018-11-12 09:04:07"))
insertTable(
  connection = connection,
  databaseSchema = "ohdsi.scratch",
  tableName = "test",
  dropTableIfExists = TRUE,
  createTable = TRUE,
  data = data
)
querySql(connection, "SELECT * FROM ohdsi.scratch.test;")
# DT
# 1 2018-11-12 06:04:07
res <- dbSendQuery(connection, "SELECT * FROM ohdsi.scratch.test;")
columnInfo <- dbColumnInfo(res)
dbClearResult(res)
as.character(columnInfo$field.type)
# [1] "TIMESTAMPNTZ"
disconnect(connection)
```
This also occurs with the latest JDBC driver (3.13.28)

@konstjar: Any thoughts how to solve this?

**Comment by konstjar** [comment]
@schuemie Snowflake has 3 different TIMESTAMP formats
https://docs.snowflake.com/en/sql-reference/data-types-datetime#timestamp-ltz-timestamp-ntz-timestamp-tz

It looks like the data entry happens with TIMESTAMP**NTZ**, but when you do select, it takes TIMESTAMP**LTZ**.

Can you run this code:
```
ALTER SESSION SET TIMESTAMP_TYPE_MAPPING = TIMESTAMP_NTZ;
```
and run select query again and compare output just to double check my assumption?

**Comment by schuemie** [comment]
@konstjar : I tried, and it makes no difference. The problem persists

**Comment by konstjar** [comment]
@schuemie one more request, could you please share output for this query?

```
show parameters like '%timezone%' in account;
```

**Comment by schuemie** [comment]
Here you go:
```
                             KEY               VALUE             DEFAULT LEVEL
1 JDBC_FORMAT_DATE_WITH_TIMEZONE                true                true      
2      JDBC_USE_SESSION_TIMEZONE                true                true      
3                       TIMEZONE America/Los_Angeles America/Los_Angeles      
                                                                                                                                                  DESCRIPTION    TYPE
1 When true, ResultSet#getDate(int columnIndex, Calendar cal) and getDate(String columnName, Calendar cal) will display the date using the Calendar's output. BOOLEAN
2                                                                            When true, JDBC driver will not display timezone offset between JVM and session. BOOLEAN
3                                                                                                                                                   time zone  STRING
```

My machine is in the ET time-zone, so the difference with LA time would explain the 3 hours. I just don't know why this causes a problem when

1.  I INSERT and SELECT from the same machine, and 
2. The field is of type TIMESTAMPNTZ (No Time Zone)

**Comment by konstjar** [comment]
Thank you. I have the same settings and they are default.

I was playing a bit:
- when data is populated using `insertTable` from R it writes the **data with hours difference** (LTZ), though the field is created correctly (TIMESTAMP_NTZ(9))
- when I insert directly through the Snowlake console, the data is populated correctly (NTZ)

`querySQL` returns the same values as Snowlake console (NZT). So, the problem is in the way how `insert` is done in `insertTable` method.

@ssuvorov-fls Can you help to understand why?

**Comment by konstjar** [comment]
@schuemie Current investigation results:

It looks like the problem happens when R passes the data to Java code. `setTimestamp` method adjusts timezone:
https://github.com/OHDSI/DatabaseConnector/blob/main/java/org/ohdsi/databaseConnector/BatchedInsert.java#L87

We are checking the possible fix. But it means the problem is global for all dialects, not for Snowflake only.

**Comment by schuemie** [comment]
I tried the PR by @ssuvorov-fls , but now instead of losing 3 hours we gain 5?

```r
connection <- connect(connectionDetails)
data <- data.frame(dt = as.POSIXct("2018-11-12 09:04:07"))
insertTable(
  connection = connection,
  databaseSchema = "ohdsi.scratch",
  tableName = "test",
  dropTableIfExists = TRUE,
  createTable = TRUE,
  data = data
)
querySql(connection, "SELECT * FROM ohdsi.scratch.test;")
# DT
# 1 2018-11-12 14:04:07
disconnect(connection)
```

**Comment by schuemie** [comment]
That latest pull request did the trick. Thank you @ssuvorov-fls !

Will be included  in next release
