### ISSUE TITLE
Found more than one class "Microsoft SQL Server" in cache; using the first, from namespace '.GlobalEnv'

### ISSUE THREAD

**Issue by ablack3** [OHDSI/DatabaseConnector#224]
I'm seeing `Found more than one class "Microsoft SQL Server" in cache; using the first, from namespace '.GlobalEnv'` printed a whole lot. 

I think this is because the "Microsoft SQL Server" class is defined in two different packages that I have installed, DatabaseConnector and odbc.

My sense is that it is not a good idea to export a class that is also exported by another package but I could be wrong. 

Defintion in DatabaseConnector:
https://github.com/OHDSI/DatabaseConnector/blob/5176e98c8979936b2c69fce4dce6fb82315366b1/R/DBI.R#L68
https://github.com/OHDSI/DatabaseConnector/blob/5176e98c8979936b2c69fce4dce6fb82315366b1/NAMESPACE#L51

Defintion in odbc:
https://github.com/r-dbi/odbc/blob/7cdeac8af11b5d304493dcdda82c3d4f63ca3452/R/db.R#L98

Does not look like odbc exports this class though...
https://github.com/r-dbi/odbc/blob/main/NAMESPACE

All I know for sure is that this message is getting printed a lot.
<img width="837" alt="image" src="https://user-images.githubusercontent.com/10227522/222772191-85f4b807-c4c3-4e0c-8cd8-b9ab654ed865.png">

**Comment by schuemie** [comment]
Yes, I looked at this. Unfortunately, `dbplyyr` doesn't nicely export the class, it just creates it at runtime, so we can't inherit from that. I didn't see it in `odbc`, so maybe we can inherit from that. Ideally, there would be a central class that we'd all inherit from.

**Comment by ablack3** [comment]
Ok just wanted to report this. I'm not sure if it causes any real problems. Feel free to close it if there's nothing to be done.

**Comment by ablack3** [comment]
This is quite annoying. DatabaseConnector is overwriting another package's class.

<img width="1050" alt="image" src="https://github.com/OHDSI/DatabaseConnector/assets/10227522/bf2ef1c7-7313-4e71-810f-402aa59a047c">

**Comment by schuemie** [comment]
Weird. I see the warning ("Found more than one class..."), but not the error message, and I can use the `db` object just fine. 

I'll try to see if I can mimic `odbc`'s trick of dynamically creating the class (as done [here](https://github.com/r-dbi/odbc/blob/56eef6949b4c63468015cd533bd6539f952877cd/R/Connection.R#L79)). Seems less nice than a global static class definition, but may solve this problem.

**Comment by schuemie** [comment]
I have a first attempt in the [dynamic_inheritance](https://github.com/OHDSI/DatabaseConnector/tree/dynamic_inheritance) branch. The warning (and probably error) should be gone when using `odbc`. 

The error does return when `DatabaseConnector::connect()` has been called prior to using `odbc` in which case the `Microsoft SQL Server` class has been dynamically defined by DatabaseConnector. Not yet sure what to do about that.

Could you give the current version in [dynamic_inheritance](https://github.com/OHDSI/DatabaseConnector/tree/dynamic_inheritance) a try? (Check is currently throwing some warnings about missing documentation, but should not prevent testing)

**Comment by schuemie** [comment]
I like the idea of adding a OhdsiSql backend to dbplyr. I'm also thinking about the future of DatabaseConnector in general. I would like it to become more and more lightweight, as the DBI drivers are becoming more and more mature and consistent with each other. DatabaseConnector should just be there to fix the last annoying incompatibility issues between drivers, not duplicate what is already there. So perhaps we may not need an OhdsiSql backend in the end (this dynamic inheritance might allow us to use the various native backends instead of SQL translation). Just thinking out loud...

**Comment by ablack3** [comment]
Yea. we've had pretty good success using odbc in Darwin but there are still some annoying differences between databases. But overall it's good. I've had a lot of issues using odbc on Oracle so it would be nice if we could use DatabaseConnector's DBI interface for Oracle and maybe snowflake as well. Basically users can just plug in whatever DBI driver user's want to use including but not limited to DatabaseConnector.

Probably one of the biggest differences between the dbplyr translation and Sqlrender has been quoting of identifiers in SQL.

Sqlrender has to quote at least one cdm column... 
<img width="605" alt="image" src="https://github.com/OHDSI/DatabaseConnector/assets/10227522/af8b216b-3e6b-487e-a48d-d52bc5ec2423">


I've been testing cross platform code a lot lately so getting some good experience with that. Not so easy! :)
