### ISSUE TITLE
[Simba][JDBC](10220) with database connector 6.0.0 for BigQuery

### ISSUE THREAD

**Issue by mik-ohdsi** [OHDSI/DatabaseConnector#225]
I am trying to run DQD for a BigQuery instance with all packages updated and using the latest JDBC driver: SimbaJDBCDriverforGoogleBigQuery42_1.3.0.1001

Right after connecting I get the first entry:
`[Simba][JDBC](10220) Driver does not support`...

Then after the message "Processing check description: cdmTable", I get endless more of these messages.

I found this [forum post](https://forums.ohdsi.org/t/insert-problem-with-sqlrender-and-jdbc-library-for-bigquery/10780), which is why I posted this issue in database connector. Maybe @konstjar knows something?

Any additional information I could provide that would be helpful? Or is this a combination of something to be fixed in DQD?

**Comment by mik-ohdsi** [comment]
Interesting observation... As this error seems to be connected to *writing* data to BigQuery, I tried it with the DQD option "writetotable <- FALSE". Then however I get an even weirder error:
```
DBMS:
bigquery

Error:
java.sql.SQLException: [Simba][BigQueryJDBCDriver](100032) Error executing query job. Message: Transaction control statements are supported only in scripts or sessions

SQL:
select * from mimiciv_full_current_cdm_22.cdm_source;

R version:
R version 4.2.2 (2022-10-31 ucrt)

Platform:
x86_64-w64-mingw32
```
This apparently has to do with a [change in the Simba JDBC driver](https://exasol.my.site.com/s/article/BigQuery-Transaction-control-statements-are-supported-only-in-scripts-or-sessions?language=en_US) as of the version 1.3. If I add the connection string option "EnableSession=1" DQD seems to start okay, creating only a local json file. Then however we get more error messages...
 [Simba][BigQueryJDBCDriver](100032) Error executing query job. Message: Function not found: charindex at [23:25]
- probably due to something in sqlrender
```
 ...
    CASE WHEN SAFE_CAST(cdmtable.care_site_id AS FLOAT64) IS NULL THEN 0 ELSE 1 END = 1 
		    and charindex('.', cast(abs(cdmtable.care_site_id) as STRING)) != 0
...
```
[Simba][BigQueryJDBCDriver](100032) Error executing query job. Message: Only one transaction at a time is supported
-maybe due to particular restrictions in this BigQuery instance...
```
select 
  num_violated_rows, 
	case 
		when denominator.num_rows = 0 then 0 
		else 1.0*num_violated_rows/denominator.num_rows 
	end as pct_violated_rows, 
	denominator.num_rows as num_denominator_rows
from
(
	select 
	  COUNT(*) as num_violated_rows
	from
	(
		/*violatedRowsBegin*/
		select 
		  m.* 
		from mimiciv_full_current_cdm_22.measurement m
		where m.measurement_concept_id =  3020946
		  and 
		  m.unit_concept_id is not null
		  and m.value_as_number is not null 
		  and (m.unit_source_value is not null or m.unit_source_value <> '')
		/*violatedRowsEnd*/
	) violated_rows
) violated_row_count,
( 
	select 
	  COUNT(*) as num_rows
	from mimiciv_full_current_cdm_22.measurement m
	where m.measurement_concept_id =  3020946
	  and value_as_number is not null
	  and (m.unit_source_value is not null or m.unit_source_value <> '')
) denominator
```

the charindex thing I will take to sqlrender...

thanks ~ mik

**Comment by konstjar** [comment]
@mik-ohdsi I assume BigQuery JDBC v1.3.x has some incompatibility with DatabaseConnector and requires adoption. You can use v1.2.x to avoid any issues. Eg. https://storage.googleapis.com/simba-bq-release/jdbc/SimbaJDBCDriverforGoogleBigQuery42_1.2.14.1017.zip

**Comment by ablack3** [comment]
It would be helpful to update the docs to say that the current BQ driver does not work and users need to install the older driver.

**Comment by schuemie** [comment]
Next release will introduce the ability to use `downloadJdbcDrivers()` for BigQuery, which will download the correct version.

**Comment by schuemie** [comment]
That old version of the JDBC driver now throws `EPOLL_DOMAIN_CLIENT_CHANNEL_TYPE field not found` errors when I try to connect. I'm updating to the latest version (1.3.2.1003), which seems to run fine.
