### ISSUE TITLE
Error with JDBC driver when trying to create a connection using DatabaseConnector

### ISSUE THREAD

**Issue by ipiper01** [OHDSI/DatabaseConnector#228]
This is my first time using DatabaseConnector, and I am struggling to create a connection. I have used the following connection details:

connectionDetails <- DatabaseConnector::createConnectionDetails(
  dbms = "spark", 
  user = "token",
  password = "\*\*password\*\*",
  server = "\*\*server\*\*",
  pathToDriver = "~/etc/jdbc",
  port = 443,
  extraSettings = list(
    httpPath = "\*\*httppath\*\*"
    ))

conn <- DatabaseConnector::connect(connectionDetails)

When I run it I get the following message and error:

Connecting using Spark ODBC driver
Error: nanodbc/nanodbc.cpp:1021: 00000: [unixODBC][Driver Manager]Can't open lib 'Simba Spark ODBC Driver' : file not found 

I have downloaded the latest SparkJDBC42 driver into the location specified in pathToDriver, but it seems like it is not using this driver. 

Any help would be appreciated, thanks!

**Comment by gongliangz** [comment]
http://ohdsi.github.io/DatabaseConnector/articles/Connecting.html#obtaining-drivers

**Comment by ipiper01** [comment]
> http://ohdsi.github.io/DatabaseConnector/articles/Connecting.html#obtaining-drivers

I have tried doing downloading the driver this way, but when I run the connection code I still get the same error message.

DatabaseConnector::downloadJdbcDrivers(
  dbms = "spark",
  pathToDriver = "~/etc/jdbc"
)

**Comment by schuemie** [comment]
Spark support is not yet mature. Right now I've set it so that if you provide a connection string, it will connect using JDBC. If you provide the server argument, it will use ODBC instead. 

In your error message, you can see that it is looking for the ODBC driver, and can't find it. You can download the driver from here: https://www.databricks.com/spark/odbc-drivers-download
