### ISSUE TITLE
insertTable fails if NAs are present in the data

### ISSUE THREAD

**Issue by vojtechhuser** [OHDSI/DatabaseConnector#23]
the insert data feature is very important.

When my data has NAs, it fails )(throws an errro).

I have to do ```data[is.na(data)] <- 0``` to work around it. But the data type is an issue. Could native support for NA be somehow added?

error:

```
Error in rJava::.jnew("java/lang/String", as.character(row[i])) : 
  java.lang.NullPointerException
```

NAs came to be because the source table where the data.frame came from had NULL there. 

so idealy NAs would become NULLs.

**Comment by schuemie** [comment]
I just pushed a new version that should fix this. Could you try it?

Remember to first close all instances of R, open only one, and then run
```
library(devtools)
install_github("ohdsi/DatabaseConnector") 
```

**Comment by vojtechhuser** [comment]
fix works.
Thank you!



```
tta<-data.frame(a=NA,b=1)
library(Achilles)
insertTable(conn,'test',tta)
querySql(conn,'select * from test')


```
