### ISSUE TITLE
Allow rethrowing of errors

### ISSUE THREAD

**Issue by mgirlich** [OHDSI/DatabaseConnector#235]
I found this while working on https://github.com/tidyverse/dbplyr/issues/1186.

``` r
con <- DatabaseConnector::connect(
  dbms = "postgresql",
  server = server,
  user = user,
  password = password
)
#> Connecting using PostgreSQL driver

tryCatch(
  DBI::dbSendQuery(con, "SELECT 1 + a"),
  error = function(cnd) {
    rlang::abort("Rethrow.", parent = cnd)
  }
)
#> Error in ._jobjRef_dollar(x[["jobj"]], name): no field, method or inner class called 'use_cli_format'
```

<sup>Created on 2023-04-25 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

I first opened an issue in rlang: https://github.com/r-lib/rlang/issues/1619 but it seems to be a DatabaseConnector issue.

**Comment by schuemie** [comment]
I've seen this behavior too. Basically, any error thrown by DBI when using DatabaseConnector causes this message. It seems some interaction between DBI or dbplyr with DatabaseConnector. I'm not sure where it is coming from. Any help solving this would be greatly appreciated.

**Comment by mgirlich** [comment]
Quoting from the rlang issue

> There may be a condition class somewhere in the DB stack that throws errors when accessing unknown `[[` fields. If that is the case I think that's a design issue with the class.

**Comment by schuemie** [comment]
So I think what you're saying is the issue really lies with rJava, which is throwing the errors that are causing the issues here. I've now added [this workaround](https://github.com/OHDSI/DatabaseConnector/blob/develop/R/DBI.R#L263-L275) to the develop branch, that rethrows the rJava error simply by taking its message (not ideal). This seems to solve this issue, but ideally rlang and rJava should get to an agreement on what is a valid error.

**Comment by mgirlich** [comment]
@schuemie Can you add your findings regarding rJava on the rlang issue I linked above?

**Comment by schuemie** [comment]
Sure! Done
