### ISSUE TITLE
askforpassword in createConnectionDetails prompts twice

### ISSUE THREAD

**Issue by nzurawski** [OHDSI/DatabaseConnector#237]
When using rstudioapi::askforpassword to fill in the password parameter in createConnectionDetails and later calling the connectionDetails object in the connect function causes two password prompts instead of just the one. 

Example:
connectionDetails <- DatabaseConnector::createConnectionDetails(dbms = "sql server",
                                                                connectionString = 'jdbc:sqlserver://server:1433;databaseName=$NAME;integratedSecurity=true;authenticationScheme=JavaKerberos',
                                                                user = 'user',
                                                                password=rstudioapi::askForSecret("network_password"),
                                                                pathToDriver = "path")
conn <- connect(connectionDetails)

Simply creating the connectionDetails object does not cause a password prompt but calling the object via the connect function at any other point will cause two password prompts instead of one. Is there something in the connect function causing the prompt to be triggered twice?

**Comment by schuemie** [comment]
For security reasons, connectionDetails does not store the password itself, but stores wherever the password came from, and will only fetch at the time it needs it. If you want to disable this, you can force evaluation using the '!!' syntax when creating connectionDetails:

```r
connectionDetails <- DatabaseConnector::createConnectionDetails(
    dbms = "sql server",
    connectionString = "jdbc:sqlserver://server:1433;databaseName=$NAME;integratedSecurity=true;authenticationScheme=JavaKerberos',
    user = 'user',
    password = !!rstudioapi::askForSecret("network_password"),
    pathToDriver = "path"
)
conn <- connect(connectionDetails)
```

**Comment by schuemie** [comment]
Note that the recommended approach is to use the `keyring` package to store your credentials securily.
