### ISSUE TITLE
Result batch issue with JDBC Connection (Snowflake) - dbFetch won't fetch all rows

### ISSUE THREAD

**Issue by KingAl** [OHDSI/DatabaseConnector#238]
`dbFetch` is ignoring the `n` parameter (e.g. `n = Inf` or `n = -1`) and returning only a subset of rows.
In contrast, a direct call to `DatabaseConnector::querySql` (and/or `DBI::dbGetQuery`) successfully retrieves all rows.

This was testing with the `snowflake-jdbc-3.13.9` driver on DatabaseConnector `6.2.1`.

For dplyr users, dbFetch is behind the scenes in a `collect()` call, and a warning is raised like: `Only first 8,041 results retrieved. Use n = Inf to retrieve all. `, but unfortunately this suggestion does not resolve the issue through either `collect` or `dbFetch`: the same issue recurs and the same warning is produced.

I presume the JDBC driver is just retrieving a single batch, sized based on the memory available to the JVM, but `querySql` working suggests this isn't a showstopper.

### Workaround
I'll note for dplyr users who run into this problem, they can just pull the connection and query out of their pipeline, and then do a `querySql`/`dbGetQuery` with it:
```
remote_collect <- function(tbl){ DBI::dbGetQuery(dbplyr::remote_con(tbl), dbplyr::remote_query(tbl)) }
result <- dplyr_tbl |> remote_collect()
```

**Comment by schuemie** [comment]
Ah, I wasn't aware `dbFetch` had a compulsory `n` argument. It is currently ignored by DatabaseConnector. I'll add code so `n=-1` and `n=Inf` are respected. Any other value and you get what we could fit in the JVM.

**Comment by KingAl** [comment]
Ah great! That doesn't sound too painful. Have really appreciated the package, thanks so much for your work 🙂
