### ISSUE TITLE
Error running DatabaseConnector within a Databricks cluster

### ISSUE THREAD

**Issue by scheah92** [OHDSI/DatabaseConnector#239]
Hi, 

I'm trying an approach where I run DQD as part of a Databricks job. This requires installing DatabaseConnector on a Databricks cluster. Currently when running `DatabaseConnector::connect()` I encounter a strange error. The output of the notebook cell shows
```
Connecting using spark driver mmap failed for CEN and END part of zip file
```
and additionally an error message
```
Error in loadJdbcDriver(driverClass, classPath): java.lang.ClassNotFoundException
``` 
I'm unable to locate any more logs regarding the java error.

Does anyone have experience running these libraries on Databricks clusters?

**Comment by schuemie** [comment]
Did you use the [downloadJdbcDrivers](http://ohdsi.github.io/DatabaseConnector/reference/downloadJdbcDrivers.html]) function to download the JDBC drivers? Is there an old JAR file in the JAR folder that might be causing the issue?

**Comment by scheah92** [comment]
Yes, I used `downloadJdbcDrivers` to get the Databricks driver. There is a postgres driver in the same /jarfolder, but I don't think that is the issue because I have no problems running these libraries inside my own EC2 instance. 

All these files and folders are cloned from my git repo, which I usually run on a separate EC2 instance. Over there everything works fine, so it's strange that when I clone the repo over on Databricks, now I'm getting an error even though I'm using the same JDBC drivers.

**Comment by schuemie** [comment]
I'm not familiar with working in DataBricks clusters. Do you know what Java version it is running?

**Comment by scheah92** [comment]
I don't remember what the default is, but they have a java 8 version that I symlink to.

After more testing, I found that running `DatabaseConnector::loadJdbcDriver(driverClass, jarPath` somehow fixes the `ClassNotFound` error. It seems that `DatabaseConnector::connect` isn't properly setting the path or loading the driver somehow, but if you explicitly do it yourself beforehand, then it'll work afterwards.
