### ISSUE TITLE
Non-Windows Platform Connection String Error to Sql Server using Windows Authentication

### ISSUE THREAD

**Issue by jose-alvarado-guzman** [OHDSI/DatabaseConnector#24]
I'm getting an invalid url error when trying to call the createConnectionDetail function from R 3.2.3 running on MAC OS X 10.11.5 to connect to SQL Server 2014 using Windows Authentication. I'm passing the following connection string to the connectionString parameter: jdbc:jtds:sqlserver://serverIP/DB;domain='domain';user='user';password='password'. We successfully connected to this SQL server instance using the mentioned connection string but with the RJDBC package. 

Previously I tried using the jdbc driver only without jtds and setting the integratedSecurity parameter to yes but this doesn't work in non-windows platforms since it needs a .dll file. I also try setting the integratedSecurity and authenticationScheme parameters to yes and JavaKerberos respectively, but this approach require configuring Kerberos and that seems like hard task. So to avoid this configuration I tried using the jdbc and jtds drivers that works with RJDBC but not with the DatabaseConnector package.

**Comment by schuemie** [comment]
Hi @jose-alvarado-guzman ,

The use of the JTDS driver is discouraged because it messes up dates. Do you need to specify the Windows domain of your user? If not, you can use the Microsoft JDBC driver instead (even without the integrated security).

**Comment by jose-alvarado-guzman** [comment]
Hi @schuemie,

Thanks for your response, I tried with and without the domain but neither way the server was able to authenticate me. The exceptions were entrusted domain and login failed respectively. According to the following [Microsoft Developer post](https://blogs.msdn.microsoft.com/psssql/2015/01/09/jdbc-this-driver-is-not-configured-for-integrated-authentication/) when connecting to Sql Server using Windows Authentication from a non-Windows platform the connection string needs the integrated security parameter set to true, the authentication schema needs to be set to JavaKerberos and the JDBC driver should be version 4.0 or above. This also requires configuring Kerberos which I had never done before and was trying to avoid using the jtds driver. Is using Kerberos the only way to authenticate from non-windows platforms to SQL Server using Windows Authentication since jtds is discouraged?

**Comment by schuemie** [comment]
Hi @jose-alvarado-guzman ,

If you don't need to provide the domain, you should be able to log in without integrated security. Did you try not providing the connection string but just setting the dbms, server, (port), user, and password arguments of either `createConnectionDetails` or `connect`?

**Comment by jose-alvarado-guzman** [comment]
Hi @schuemie,

Yes I tried using the createConnectionDetail function setting the dbms, server, port, user and password without the domain and then passing that object to the connect function but the login failed.

**Comment by schuemie** [comment]
You said you managed to connect with RJDBC and jtds. Do you think you could try making it work through RJDBC with the Microsoft JDBC driver instead?
