### ISSUE TITLE
Error executing SQL: 'origin' must be supplied

### ISSUE THREAD

**Issue by anthonysena** [OHDSI/DatabaseConnector#240]
Using DatabaseConnector v6.2.2 to execute a query against our OMOP CDM hosted on Redshift, I'm encountering the error below. Here is a query that provides a reproducible example:

```r
DatabaseConnector::querySql(connection = connection, "SELECT source_release_date FROM cdm.cdm_source;")

Error in `.createErrorReport()`:
! Error executing SQL:
'origin' must be supplied
An error report has been created at  D:/errorReportSql.txt
Run `rlang::last_trace()` to see where the error occurred.
```

Digging into this, I've found the following R code to be problematic:

https://github.com/OHDSI/DatabaseConnector/blob/2da5b9b3d04d8d6753d4078804713989a03abca0/R/Sql.R#L115-L119

For reference, this is the previous version of this code section: https://github.com/OHDSI/DatabaseConnector/blame/1266bf221ddfd294409818ad3a6d78eae2cca14a/R/Sql.R#L149-L157

It appears that in v6.2.2, the integer representation for the date is captured via the `rJava` but then the `as.Date` conversion fails since we do not have a reference `origin` date to use. Based on the commit message, this change was made to improve performance but perhaps in this case we should revert back to the original string approach to avoid this problem?

**Comment by DrTTrousers** [comment]
Can confirm we get this on snowflake too.

We've reverted to 6.2.1 to counter

**Comment by schuemie** [comment]
Yes, sorry, this does not happen in the latest versions of R, which is why I didn't detect it before. I'll release a fix shortly.

**Comment by schuemie** [comment]
Should be fixed in the new release
