### ISSUE TITLE
Bug with DatabaseConnector::renderTranslateExecuteSql

### ISSUE THREAD

**Issue by Siting-Wang** [OHDSI/DatabaseConnector#242]
DatabaseConnector::renderTranslateExecuteSql always is interpreting “COMPUTE STATS” statement to “COMPUTE _stats” in R studio, but DatabaseConnector::executeSql seems works fine with “COMPUTE STATS” statement. Similar situation with 'show table stats' statement. Please see the sample codes and error log below. Could this be fixed? Thanks!

Codes:

sql <- paste0("show table stats ", tableName, ";")
DatabaseConnector::executeSql(connection = conn, sql)

DatabaseConnector::renderTranslateExecuteSql(conn,
                                             sql = paste0("show table stats ", tableName, ";")
)

Logs:
> sql <- paste0("compute   stats  ", tableName, ";")
> DatabaseConnector::executeSql(connection = conn, sql)
  |================================================================================================================================| 100%
Executing SQL took 0.849 secs
> DatabaseConnector::renderTranslateExecuteSql(conn,
+                                              sql = paste0("show table stats ", tableName, ";")
+ )
  |                                                                                                                                |   0%Error in `.createErrorReport()`:
! Error executing SQL:
java.sql.SQLException: [Cloudera][ImpalaJDBCDriver](500051) ERROR processing query/statement. Error Code: 0, SQL state: TStatus(statusCode:ERROR_STATUS, sqlState:HY000, errorMessage:ParseException: Syntax error in line 1:
show table _stats rwd_temp.wsx...
           ^
Encountered: IDENTIFIER
Expected: STATS

CAUSED BY: Exception: Syntax error

**Comment by schuemie** [comment]
The ` renderTranslateExecuteSql()` function first translates from OhdsiSql, and `COMPUTE STATS` is not valid OhdsiSql. Please use `UPDATE STATISTICS my_table;` instead, which will translate to `COMPUTE STATS my_table;` on Impala.

**Comment by Siting-Wang** [comment]
Great! UPDATE STATISTICS works well. How about the correct statement for 'show table _stats'? Thanks!

**Comment by schuemie** [comment]
I don't think there's a consistent implementation of `SHOW TABLE STATS` across the various DBMSs, so that is not currently support.

**Comment by Siting-Wang** [comment]
Thanks a lot for the information! UPDATE STATISTICS is more critical for my situation. It's OK to skip SHOW TABLE STATS.
