### ISSUE TITLE
Question: what happens to running query when program exits unexpectedly

### ISSUE THREAD

**Issue by RowanErasmus** [OHDSI/DatabaseConnector#243]
Hi,

I am wondering if DatabaseConnector has any mechanism of terminating running queries if an R process exits unexpectedly.

Is this something which is driver / database specific or does DatabaseConnector gracefully terminate running queries before dying.

Thanks!

**Comment by schuemie** [comment]
Whether queries are terminated if the R process stops depends on the driver. DatabaseConnector does not explicitly do this.

Note that for connections (not queries), the recommended practice is to use an `on.exit()` clause to close the connection if something were to happen (see for example [here](https://github.com/OHDSI/CohortMethod/blob/main/R/DataLoadingSaving.R#L163-L164)).

**Comment by RowanErasmus** [comment]
Thanks for the fast response and suggestion to use on.exit() and at least close the connection, it is a good start.
