### ISSUE TITLE
Consider not throwing a warning when passing already translated sql to dbGetQuery or dbExecute.

### ISSUE THREAD

**Issue by ablack3** [OHDSI/DatabaseConnector#245]
Hi @schuemie,

I would like to be able to use DatabaseConnector as a plain vanilla database driver that delivers SQL to the database and delivers the result back to my R session. I'd like to use the DBI interface that database connector provides. As you know dbGetQuery will automatically run the SQL through SqlRender's translation function. User can skip this by first translating the SQL and then passing the SQL to dbGetQuery. However passing already translated SQL to DatabaseConnector::dbGetQuery generates a warning. While this can be easily ignored it can cause issues when running R check.

I'm wondering why DatabaseConnector needs to throw a warning when accepting already translated SQL and if you'd be open to the idea of not throwing a warning in this case or providing an argument in the DBI interface to just send SQL and return the result without translation or throwing a warning.

What do you think?

**Comment by ablack3** [comment]
``` r
library(DatabaseConnector)

con <- DBI::dbConnect(
  DatabaseConnectorDriver(),
  dbms = "sqlite",
  server = Eunomia::getEunomiaConnectionDetails()$server())
#> Connecting using SQLite driver


sql <- "select count(*) as n from main.person;"
sql <- SqlRender::translate(sql, "sqlite")

DBI::dbGetQuery(con, sql)
#> Warning: Input SQL has already been translated, so not translating again
#> This warning is displayed once every 8 hours.
#>      n
#> 1 2694

DBI::dbDisconnect(con)

packageVersion("DatabaseConnector")
#> [1] '6.2.3'
```

<sup>Created on 2023-08-18 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by schuemie** [comment]
I'm not following your use case. The idea is that you don't have to call `translate` before calling `dbGetQuery()`, that DatabaseConnector is just a DBI driver that understands OhdsiSql. Why would you call `translate`?

**Comment by ablack3** [comment]
The use case is to send SQL to the database through DatabaseConnector's DBI interface without translation. Just take my SQL, execute it, and give me the result. Nothing more.

**Comment by schuemie** [comment]
But the idea of DatabaseConnector (since v6) is that it provides a unified interface, talking OhdsiSql across all platforms.

A special case (which you appear to want to use) is to use the underlying drivers without translation. To support that I added a `translate` argument (at your request). So 

```r
DBI::dbGetQuery(con, sql, translate = FALSE)
```

Should work fine in your example, and not throw the warning.

**Comment by ablack3** [comment]
Yes that makes sense. My use case is different since I want to skip translation. Thank you very much for adding that argument to dbGetQuery! 🙏 Very much appreciated.
