### ISSUE TITLE
UCASE call in querySql

### ISSUE THREAD

**Issue by vojtechhuser** [OHDSI/DatabaseConnector#25]
We have conflicting conventions.
In other discussion - we discuss CamelCase/SnakeCase for SQL and R, yet I kind of like this radical solution the querySql function does.

See below.

Do we want this to stay or be removed ?
I am not sure I like different names in R and SQL. I would not want to call always in this function the Camel-Snake conversion. (also it drops capital letters in 2+1 as grandTotal (into GRANDTOTAL)

I can live with default toupper(). current behaviour (althoug for typing (having RSI) - I would prefer tolower() :-) 

```
querySql <- function(connection, sql) {
  tryCatch({
    rJava::.jcall("java/lang/System", , "gc")  #Calling garbage collection prevents crashes
    
    result <- lowLevelQuerySql(connection, sql)
    colnames(result) <- toupper(colnames(result))
    return(result)
  }, error = function(err) {
    writeLines(paste("Error executing SQL:", err))
```

**Comment by schuemie** [comment]
querySql currently does not alter the variable names, but in all OHDSI packages we now have the convention that after calling querySql we will automatically convert snake_case to camelCase. 

If we don't do that, but follow your suggestion that we simply convert camel_case to UPPER_CASE_SNAKE_CASE, the consequence would be that all our R code will now have a mixture of naming conventions. Variables derived from a database would be SNAKE_CASE, while other variables would use camelCase. This gets really complicated when DATABASE_VARIABLES are modified in R. Should they then still be SNAKE_CASE, or camelCase? 

The current solution guarantees we have only 1 naming convention in SQL, and only 1 in R.

**Comment by vojtechhuser** [comment]
The current version calls toupper(). Unless I am reading something wrong.

**Do we want this to stay or be removed ?**
![image](https://cloud.githubusercontent.com/assets/7526119/17366079/56a07b0e-5957-11e6-9820-3a1e5e46a5e1.png)

**Comment by chrisknoll** [comment]
If it changes, we'll have a significant amount of re-write to do, and apps will break until the rewrite is complete.  If we want to make this change, it's going to have to be done in a special branch, and all dependent apps will need to coordinate all their releases based on this change.

**Comment by schuemie** [comment]
Ah yes, I forgot about the ucase. The reason why I added is that some dbmss convert all names to upper case, some convert all to lower case, and some maintain the case of the original 'create table' statement. At least with the ucase, behavior across platforms is consistent.

Note that SqlRender's snakeCaseToCamelCase function ignores the case of the input. Most code would therefore be unaffected if we remove this.

Could you give me a use case why the ucase should be removed? Remember that this means that behavior will then be different across platforms, and the user will need to deal with that.

**Comment by vojtechhuser** [comment]
OK. I am glad that I was correct in reading the current code. 
I vote for leaving everything as is. 

BUT - we should clearly say that users should expect always uppercased output when using DatabaseConnect querySql()
