### ISSUE TITLE
Optional method of using Ibis backend connectors

### ISSUE THREAD

**Issue by haydenbspence** [OHDSI/DatabaseConnector#252]
This is a suggestion for a feature enhancement. 

The [Ibis Project](https://ibis-project.org/) is a Python library that provides a lightweight, universal interface for data wrangling with the support of 15+ popular backends. Wes McKinney is a co-founder, better known for his authorship of the Pandas library, and Ibis is actively maintained by 100+ contributors. 

If someone has both R and Python installed, is it feasible create a method that calls Ibis within DatabaseConnector? For example through Reticulate in such a way that these additional backends that Ibis supports can be used? Potentially by using a pass-through common database like DuckDB? This could significantly reduce the amount of backends needing active support by DatabaseConnector while still offering support so long as Python is able to be installed alongside R.

**Comment by ablack3** [comment]
Personally I think this would be better for a DatabaseConnector/SqlRender component in python. It's an interesting idea to bring it into R...
