### ISSUE TITLE
install issue

### ISSUE THREAD

**Issue by leeanhu789** [OHDSI/DatabaseConnector#26]
Dear All,
I received the following error message while installing DatabaseConnector
"
Error : .onLoad failed in loadNamespace() for 'rJava', details:
  call: fun(libname, pkgname)
  error: No CurrentVersion entry in Software/JavaSoft registry! Try re-installing Java and make sure R and Java have matching architectures.
Error : package 'rJava' could not be loaded
Error: loading failed
Execution halted
ERROR: loading failed for 'x64'
- removing 'C:/Users/llu/Documents/R/win-library/3.3/DatabaseConnector'
  "
  I am running R for 32.bit, and i think I do not have privilege to install these packages to where R program is located (C:\Program Files\R\R-3.3.1). I did install rJava and seemed successful, but rJava is under the following folder: C:\Users\llu\Documents\R\win-library\3.3\rJava

Could someone advise what I am missing here for not being able to install DatabaseConnector package?

Thanks a lot!
Lian

**Comment by schuemie** [comment]
Hi @leeanhu789 ,

The error message states that rJava can't find Java (rJava can actually be installed without Java, but when you try to load it it will fail).

In this case, since you're saying you're running 32-bit R (why? ;-) ), and the message mentions a 64-bit architecture, I'm guessing you don't have the 64-bit version of Java installed, but R is looking for it.

If you're sticking to the 32-bit architecture, you could force R to only install the 32-bit version of the package:
```r
install.packages("drat")
drat::addRepo("OHDSI")
install.packages("DatabaseConnector", INSTALL_opts="--no-multiarch")
```

Hope this helps.

**Comment by leeanhu789** [comment]
Thank you very much for your kind help Martijn. You are right. Since I did not have 64-bits JAVA at work, I tried to run 32-bit R and install the package. I am working with IT to solve the JAVA issue.
However, on home computer, I also have installation issue.  I have 64-bit JAVA and run 64-bit R. I also set up the R environment based on wiki on:  http://www.ohdsi.org/web/wiki/doku.php?id=documentation:r_setup 

I still cannot install DatabaseConnector, and received the following error message:

*** arch - x64
ERROR: loading failed for 'i386'
* removing 'C:/Users/HU/Documents/R/win-library/3.3/DatabaseConnector'

The downloaded source packages are in
        ‘C:\Users\HU\AppData\Local\Temp\RtmpIH24dp\downloaded_packages’
Warning messages:
1: running command '"C:/R/R-3.3.1/bin/x64/R" CMD INSTALL -l "C:\Users\HU\Documents\R\win-library\3.3" C:\Users\HU\AppData\Local\Temp\RtmpIH24dp/downloaded_packages/DatabaseConnector_1.7.0.tar.gz' had status 1 
2: In install.packages("DatabaseConnector") :
  installation of package ‘DatabaseConnector’ had non-zero exit status

What may go wrong this time? Thank you again. By the way, I enjoyed reading your paper "Replication of the OMOP Experiment in Europe..." and "Methods for drug safety signal detection in longitudinal
observational databases: LGPS and LEOPARD".

**Comment by leeanhu789** [comment]
Hi Schuemie,
Just to note that I was able to install DatabaseConnector on my 64-bits home computer with 64-bits JAVA  using the statements in your last comments:

install.packages("drat")
drat::addRepo("OHDSI")
install.packages("DatabaseConnector", INSTALL_opts="--no-multiarch")

 I am working on the work computer now, and will let you know how it goes. Thank you very much.

Lian

**Comment by schuemie** [comment]
Thanks! Yes, I think on your home computer you had the opposite problem: you're running 64-bit R and really only need the 64-bit Java (which you have), but `install.packages` also wanted to create the 32-bit version of the package. Glad the code solved the problem!
