### ISSUE TITLE
Call to Andromeda causing unit tests to fail

### ISSUE THREAD

**Issue by azimov** [OHDSI/DatabaseConnector#260]
[This line ](https://github.com/OHDSI/DatabaseConnector/blob/be58698d06b2d03940117c7bc5cf7aa1126fec8a/R/InsertTable.R#L221) calls Andromeda::isAndromeda which won't be present in setups where Andromeda isn't required.

As an alternative I propose simply calling:

```r
inherits(x, "Andromeda")
```

**Comment by schuemie** [comment]
Yes, sorry about that. I have a fix in develop. Will release shortly.
