### ISSUE TITLE
How to add connection scripts in connectionDetails object?

### ISSUE THREAD

**Issue by mdlavallee92** [OHDSI/DatabaseConnector#268]
I am using a snowflake database and when I connect I have to run two commands at the start of my connection or else it returns errors when I pass `connectionDetails` into a function of a HADES package:

``` sql
ALTER SESSION SET JDBC_QUERY_RESULT_FORMAT='JSON';
USE SCHEMA @temp_emulation_schema;
USE ROLE @user_role;
```

The first line deals with this [issue](https://community.snowflake.com/s/article/Getting-java-lang-NoClassDefFoundError-for-class-RootAllocator). The second line is not totally necessary if you specify a tempEmulationSchema in SqlRender but can still be helpful. The third line Ive encountered on occasion. Although I know I can specify the role and the schema in the construction of the connection string, I am just not sure if the same can be done for the query format. 

Is there a way to add a connection script into the connection details object to run at the point of connection? 

Currently I just run `DatabaseConnector::executeSql` with these lines once the connection is open and pass an open connection to a HADES function. However, I am curious if you can pass a connection script into the `connectionDetails` so that I pass `connectionDetails` instead of an open connection into a HADES function.

**Comment by schuemie** [comment]
According to the Snowflake documentation, you can set the default schema and role as part of the connection string (see [here](https://docs.snowflake.com/en/developer-guide/jdbc/jdbc-parameters#role)). 

The first one is not a formally documented property of the connection string, but [this](https://www.ibm.com/support/pages/snowflake-jdbc-javalangindexoutofboundsexception-error-when-cognos-analytics-running-aix) says this should work: `jdbc_query_result_format=json`.

So if your current connection string is something like
```
jdbc:snowflake://abc123.us-east-1.snowflakecomputing.com?db=MY_DATASET&warehouse=COMPUTE_WH_XS
```
You should be able to change it to:
```
jdbc:snowflake://abc123.us-east-1.snowflakecomputing.com?db=MY_DATASET&warehouse=COMPUTE_WH_XS&jdbc_query_result_format=json&schema=MY_SCHEMA&role=MY_ROLE
```

Could you give that a try?

Also, out of curiosity, why do you need to set the results format to JSON? I don't need to do that on the testing server I have.

**Comment by mdlavallee92** [comment]
great this worked for the query format! 😎 I knew you could add things like the schema, warehouse etc in the string, but was wondering if a connecting script was in scope of DatabaseConnector. This solution is perfectly fine though. 

Personally, I have not seen this query format issue when using `DatabaseConnector`. I have seen it error out when I am working on a 3rd party sql client so I have added the json format toggle as a solution. But others have seen errors relating to the query format when applying `DatabaseConnector` (@alondhe may be able to speak on his experience). 

My guess is it is related to how we have snowflake setup at our site. I do not know enough about database administration to say anything more than that. 

Closing out the issue, since my question was answered.
