### ISSUE TITLE
failed to install ‘FeatureExtraction’ ‘CohortMethod’   

### ISSUE THREAD

**Issue by leeanhu789** [OHDSI/DatabaseConnector#27]
Dear All,

I received this message when trying to install these two packages : 
 install.packages("CohortMethod", INSTALL_opts="--no-multiarch", dependencies=TRUE)
install.packages("FeatureExtraction", INSTALL_opts="--no-multiarch", dependencies=TRUE)

"Warning: unable to access index for repository https://OHDSI.github.io/drat/bin/windows/contrib/3.3:
  cannot open URL 'https://OHDSI.github.io/drat/bin/windows/contrib/3.3/PACKAGES'
Packages which are only available in source form, and may need compilation of C/C++/Fortran:
  ‘FeatureExtraction’ ‘CohortMethod’
  These will not be installed"

My goal is to install package "KeppraAngioedema", which apparently requires the above two packages as dependencies.  I tried 64-bits, 32-bits R with 64-bits JAVA JDK, JRE etc. 

Thank you for your help!
Lian

**Comment by schuemie** [comment]
Hi @leeanhu789 ,

Did you install [RTools](https://cran.r-project.org/bin/windows/Rtools/)? Both FeatureExtraction and CohortMethod contain C++ code that requires RTools to compile.

Cheers,
Martijn

**Comment by leeanhu789** [comment]
Hi Martijn,
Thanks so much for all the help. I did install RTools on both the home and work computer, but somehow on both computers, I failed to install these two packages.  Would the version of the R or version of the RTools matter? I think I installed the newest version of RTools (Rtools34.exe) on home computer, and Rtools33.exe on work computer.
By the way, is there any data set that we can use to run all the R codes in KeppraAngioedema project?

Thank you!
Lian

**Comment by schuemie** [comment]
Hi Lian,

Digging a bit deeper, it seems there's a problem installing the packages on the latest version of R (>=3.3.0)! I can easily reproduce it on my machine. I'm looping in @msuchard , since he knows most about `drat`, which seems to be causing the problems.

In the mean time, you can use `devtools` to install the packages instead:
```r
install.packages("devtools", "Cyclops", "SqlRender")
library(devtools)
install_github("ohdsi/OhdsiRTools", args = "--no-multiarch") 
install_github("ohdsi/DatabaseConnector", args = "--no-multiarch")
install_github("ohdsi/FeatureExtraction", args = "--no-multiarch") 
install_github("ohdsi/CohortMethod", args = "--no-multiarch")
install_github("ohdsi/OhdsiSharing", args = "--no-multiarch")

# You may want to skip this one for now:
install.packages("aws.s3", repos = "http://cloudyr.github.io/drat")

install_github("ohdsi/StudyProtocols/KeppraAngioedema", args = "--no-multiarch")
```

One dataset you can use just to run the code is the [Synpuf dataset in CDM format](http://www.ltscomputingllc.com/downloads/) created by Lee Evans. You would need to load the dataset into a database.

Cheers,
Martijn

**Comment by leeanhu789** [comment]
Hi Martijn,
Awesome. Thanks for your help.  All are installed fine now, in both R 3.2.4 32bit (work computer) and R 3.3.1. 64 bits (home computer).  I wonder whether the problem was that I had not install OhdsiRTools as instructed here in your note.  Instead, I had only installed RTools in the root directory as instructed on OSDHI wiki regarding R environment set up (http://www.ohdsi.org/web/wiki/doku.php?id=documentation:r_setup). 

Thank you so much!

Lian
