### ISSUE TITLE
java.sql.SQLFeatureNotSupportedException

### ISSUE THREAD

**Issue by andtsouch** [OHDSI/DatabaseConnector#270]
Hi, I am using DatabaseConnector6.3.2 and I am having the following error when executing the DatabaseConnector::executeSql() function:

print(connectionDetails$dbms)
sql <- SqlRender::readSql("./cohort.sql") 
sql <- SqlRender::render(sql,
              cdm_database_schema = cdmDatabaseSchema,
              #vocabulary_database_schema = cdmDatabaseSchema,
              target_database_schema = cohortsDatabaseSchema,
              target_cohort_table = cohortTable,
              target_cohort_id = targetID)  
sql <- SqlRender::translate(sql, targetDialect = connectionDetails$dbms)
DatabaseConnector::executeSql(connection, sql)

**Error:**
 |                                                                      |   0%Error in `.createErrorReport()`:
! Error executing SQL:
java.sql.SQLFeatureNotSupportedException: Method org.postgresql.jdbc.PgStatement.executeLargeUpdate is not yet implemented.
An error report has been created at  errorReportSql.txt
Backtrace:
└─DatabaseConnector::executeSql(connection, sql)
   └─base::tryCatch(...)
      └─base (local) tryCatchList(expr, classes, parentenv, handlers)
         └─base (local) tryCatchOne(expr, names, parentenv, handlers[[1L]])
            └─value[[3L]](cond)
               └─DatabaseConnector:::.createErrorReport(dbms, err$message, sqlStatement, errorReportFile)
                  └─rlang::abort(...)
Execution halted

**errorReportSql.txt:**

DBMS:
postgresql

Error:
java.sql.SQLFeatureNotSupportedException: Method org.postgresql.jdbc.PgStatement.executeLargeUpdate is not yet implemented.

SQL:
CREATE TEMP TABLE Codesets  (codeset_id int NOT NULL,
  concept_id bigint NOT NULL
)

R version:
R version 4.2.0 (2022-04-22)

Platform:
x86_64-pc-linux-gnu

Attached base packages:
- stats
- graphics
- grDevices
- utils
- datasets
- methods
- base

Other attached packages:
- DatabaseConnector (6.3.2)
- PatientLevelPrediction (6.3.6)

**Comment by schuemie** [comment]
Which Postgres JDBC driver version are you using (see your jar folder)? The [recommended version](https://github.com/OHDSI/DatabaseConnector/blob/main/R/Drivers.R#L93) is V42.2.18, which is what DatabaseConnector will download if you ask it to.

**Comment by andtsouch** [comment]
I have postgres 12 installed inside a docker container, but I can't find information about its JDBC driver. Is there also a postgres version that is recommended? I am guessing from the recommended driver version that it must be the latest.
