### ISSUE TITLE
load date format (yyyymmdd, e.g. 20091001) from sample CDM format csv file into oracle database  

### ISSUE THREAD

**Issue by leeanhu789** [OHDSI/DatabaseConnector#28]
Dear All,
I am trying to load Lee Evans provided CDM format csv files into my database.   I encountered one problem.  Hope someone advise.

some csv data files (e.g. CDM_death.csv,  CDM_visit_occurrence.csv) have dates columns, but the format is yyyymmdd., e.g. 20080413).  In oracle.sql,   the format for DEATH_DATE column for DEATH table is defined as "date".  The sqlldr failed to load the this numerical format "yyyymmdd"  into DEATH table.
I thought there must be a reason Lee Evans  used this kind of numerical format in the csv file.

Could someone advise how to load this type of format as a date format into oracle database?  I am using sqlplus.
Thank you very much in advance!
Lian

**Comment by blm14** [comment]
Oracle actually stores dates as a series of bytes not a string like MySQL or other databases. You have to wrap all dates in oracle in TO_DATE with an argument specifying what format the date string is in. in this case it would be

To_date(name_of_column,’YYYYMMDD’)

Are you using SQL*Loader or command line sqlldr?

**Comment by leeanhu789** [comment]
@blm14 ,
Thank you for your help. I am using SQL*Loader, not in command line. I will follow your instruction and let you know the result. Thank you again for your kind help.
Lian
