### ISSUE TITLE
Issue with the connect() function

### ISSUE THREAD

**Issue by malihamashkoor123** [OHDSI/DatabaseConnector#281]
Hi 

I am trying to connect to the pgadmin database using the createConnectionDetails() and connect() function from the DatabaseConnector package. However, the system is hanging and is unable to connect to the database:

 
![image](https://github.com/user-attachments/assets/b2857d4c-9bf0-4779-b2d3-363b09df5b05)

My session Info is as follow:

![image](https://github.com/user-attachments/assets/1bfe6df8-aad4-473b-ac22-6e2e8d063e12)

Can you pls tell me how to resolve this error?

**Comment by schuemie** [comment]
I suspect it either an issue with the JDBC driver, or a network (firewall) issue. 

Are you using the JDBC driver installed by the [`downloadJdbcDrivers()`](https://ohdsi.github.io/DatabaseConnector/reference/downloadJdbcDrivers.html) function?

Are you able to connect successfully with the JDBC driver in another program such as [SqlWorkbench](https://www.sql-workbench.eu/)?
