### ISSUE TITLE
Remove temp table emulation for Oracle

### ISSUE THREAD

**Issue by schuemie** [OHDSI/DatabaseConnector#290]
Oracle already supports real temp tables for some years now

**Comment by schuemie** [comment]
This is actually false. Oracle still doesn't properly support temp tables

**Comment by cgreich** [comment]
Is there anybody left using Oracle? Clair might now. I haven't seen or heard of such a thing in a long time. Everybody is on Postgres, Snowflake, Redshift, SQL Server or Google Big Query. Maybe time to abandon that thing? Larry doesn't need another yacht.
