### ISSUE TITLE
Error while connecting to mysql using connect() method

### ISSUE THREAD

**Issue by krishnamedikeri** [OHDSI/DatabaseConnector#30]
`install.packages("drat")
Warning in install.packages :
  cannot open URL 'https://OHDSI.github.io/drat/bin/windows/contrib/3.3/PACKAGES.gz': HTTP status was '404 Not Found'
Warning in install.packages :
  cannot open URL 'https://OHDSI.github.io/drat/bin/windows/contrib/3.3/PACKAGES': HTTP status was '404 Not Found'
Warning in install.packages :
  unable to access index for repository https://OHDSI.github.io/drat/bin/windows/contrib/3.3:
  cannot open URL 'https://OHDSI.github.io/drat/bin/windows/contrib/3.3/PACKAGES'
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.3/drat_0.1.1.zip'
Content type 'application/zip' length 72297 bytes (70 KB)
downloaded 70 KB

package ‘drat’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
    C:\Temp\Rtmp4eeek4\downloaded_packages

> drat::addRepo("OHDSI")
> install.packages("DatabaseConnector")
> Warning in install.packages :
>   cannot open URL 'https://OHDSI.github.io/drat/bin/windows/contrib/3.3/PACKAGES.gz': HTTP status was '404 Not Found'
> Warning in install.packages :
>   cannot open URL 'https://OHDSI.github.io/drat/bin/windows/contrib/3.3/PACKAGES': HTTP status was '404 Not Found'
> Warning in install.packages :
>   unable to access index for repository https://OHDSI.github.io/drat/bin/windows/contrib/3.3:
>   cannot open URL 'https://OHDSI.github.io/drat/bin/windows/contrib/3.3/PACKAGES'
> installing the source package ‘DatabaseConnector’

trying URL 'https://OHDSI.github.io/drat/src/contrib/DatabaseConnector_1.7.1.tar.gz'
Content type 'application/octet-stream' length 6967603 bytes (6.6 MB)
downloaded 6.6 MB
- installing _source_ package 'DatabaseConnector' ...
  *\* R
  *\* inst
  *\* preparing package for lazy loading
  *\* help
  **\* installing help indices
  *\* building package indices
  *\* testing if installed package can be loaded
- DONE (DatabaseConnector)

The downloaded source packages are in
    ‘C:\Temp\Rtmp4eeek4\downloaded_packages’

> library(DatabaseConnector)
> Loading required package: RJDBC
> Loading required package: DBI
> Loading required package: rJava
> 
> conn <- connect(dbms = "mysql",
> -                 server = "localhost",
> -                 user = "root",
> -                 password = "root",
> -                 schema = "sakila")
>   Connecting using MySQL driver
>   Error in .jcall(drv@jdrv, "Ljava/sql/Connection;", "connect", as.character(url)[1],  : 
>   java.sql.SQLException: Access denied for user ''@'localhost' (using password: NO)
>   `

Thanks in advance to those who solves the issue...

**Comment by schuemie** [comment]
Dropped support for MySQL.

**Comment by seonghobae** [comment]
> Dropped support for MySQL.

Why are you dropped MySQL support?

**Comment by schuemie** [comment]
Because MySQL cannot do some very basic things, like reference a temp table twice in the same SQL statement. There are superior open source alternatives such as PostgreSQL.

**Comment by kirenotneb** [comment]
@schuemie I understand that MySQL/MariaDB have a limited feature set in certain areas but I'm surprised by the decision to remove support for one of the top 5 most popular "open-source" RDBMS. It seems like it would limit the audience and adoption of this package, especially considering how poor the experience is using ODBC connections for non-Windows systems.

**Comment by schuemie** [comment]
For those interested in using MySQL in R (for things not related to OHDSI), I recommend using the [RJDBC package](http://www.rforge.net/RJDBC/).
