### ISSUE TITLE
Support Impala

### ISSUE THREAD

**Issue by tomwhite** [OHDSI/DatabaseConnector#31]
I've got a branch here: https://github.com/OHDSI/DatabaseConnector/compare/master...tomwhite:impala.

I've tested this locally, but is there a recommended way to add automated tests for new databases?

**Comment by schuemie** [comment]
We have unit tests [here](https://github.com/OHDSI/DatabaseConnector/tree/master/tests/testthat) that are part of our continuous integration process. They work against an internet-accessible server running SQL Server, PostgreSQL, and Oracle. This server is also used to test other tools like [Achilles](https://github.com/OHDSI/Achilles). Preferably we would have something similar for Impala. Would that be possible?

**Comment by schuemie** [comment]
We are trying to keep the package as lean as possible. We are working on moving the package to CRAN, but they are already not going to like the size in bytes. Any bigger and we're sure to be rejected.

Why are there all the other jar files next to the JDBC driver, like ```commons-logging-1.1.1.jar``` and ```httpclient-4.1.3.jar```? Please drop any that are not absolutely necessary for the functionality provided by the package.

**Comment by tomwhite** [comment]
Thanks @schuemie. I don't think there's a simple way to have an internet-accessible server running Impala. Would it be sufficient to document the testing process for Impala?

I understand the reluctance to add lots more JARs. They are all necessary for the Impala JDBC driver, so I think it would be better to require that they are pre-installed in a (configurable) directory on the local filesystem. This would also make it possible to use a later version of the driver without having to update DatabaseConnector with the new JARs.

**Comment by schuemie** [comment]
Just to be clear, without an Impala test server I won't be able to guarantee DatabaseConnector works (and keeps working). Any support for Impala users will need to be provided by you or others in your organization..

13.2MB of Jar files is too much to include in the package, so I agree the option is to ask users to download the driver separately. I can add functionality for users to provide the path using the ```options``` function in R. Currently, Cloudera is requiring users to [fill in a form to download the driver](http://www.cloudera.com/downloads/connectors/impala/jdbc/2-5-5.html), and then they have to pick the right files from the zip file. In my humble opinion you're not making life easy for your users. Might you consider adding an R function that will just fetch the right files for the users, similar to [this code](https://github.com/OHDSI/DatabaseConnector/blob/no-jars/R/DriverDownload.R#L35)?

**Comment by tomwhite** [comment]
Got it. I agree that from a developer point of view having to fill in a form is suboptimal, but that's where we are today. I've updated my branch to use the `options` function as you suggested (thanks for the suggestion, I didn't know what the appropriate R idiom was), so you can unzip the drivers and point the code at the directory without having to specify all the JARs separately.

PR is at https://github.com/OHDSI/DatabaseConnector/pull/32.

**Comment by msuchard** [comment]
Possible alternative solution is to refactor the `Impala` components into a separate library that extends `DatabaseConnector`.  In this manner, `DatabaseConnector` remains externally unaffected during installation and use for users who do not wish to go through the hassle of installing `Impala`.

**Comment by schuemie** [comment]
@tomwhite ,  I fetched your pull request but then modified the way the jar path is specified. I changed my mind, and figured there is no reason it shouldn't just follow the same approach as all the other parameters, so I made it arguments for the `connect` and `createConnectionDetails` functions. I am guessing we will start using that for the drivers as well to get it into CRAN. 

Can you check if everything is still working on your side?

**Comment by tomwhite** [comment]
I just checked your latest change with Impala, and it works fine. Thanks for merging it.
