### ISSUE TITLE
default schema

### ISSUE THREAD

**Issue by vojtechhuser** [OHDSI/DatabaseConnector#38]
I believe the AND condition should be an OR in this part of the code

https://github.com/OHDSI/DatabaseConnector/blob/master/R/DatabaseConnector.R#L309

In order to have the schema specified after connection, the current code requires it in both the schema argument AND in the connectionDetails$schema.  

I think the desired behaviour is that if simply just the schema parameter says 'forceit' the connection function with switch to forceit schema.

**Comment by schuemie** [comment]
Nope, it should really be an OR. Note that both conditions test the same variable: `schema`, as in the argument with which the function is called. It is simply checking two things:

1. Is the argument specified at all? (!missing)
2. Is the specified value non-null? (!is.null)

Note that the only place `connectionDetails` is used in this function is [here](https://github.com/OHDSI/DatabaseConnector/blob/master/R/DatabaseConnector.R#L185), where it is used to call the function again with the connection details as individual arguments.

**Comment by vojtechhuser** [comment]
ok. I solved the problem by setting both. (conString$schema and schema argument) and then it worked. For some reason it did not work with only schema set.  I think you meant (it should be AND).  I am using it to save me from using sqlRender but maybe I should just not be lazy and still use '@resultSchema.' and sqlrender.
