### ISSUE TITLE
How to enable SSL 

### ISSUE THREAD

**Issue by writetoritu** [OHDSI/DatabaseConnector#45]
@schuemie We have been actively using this package to connect to a variety of DBMSes in PEDSnet (please see the [function here] (https://github.com/PEDSnet/Data-Quality-Analysis/blob/master/Library/PerformDatabaseOperations.R#L37). 

I wanted to learn how to enable SSL on a postgres database through this package?
We found this [line of code] (https://github.com/OHDSI/DatabaseConnector/blob/a475dbd2cec93ce0536a7dc1017a5b18479fb456/man-roxygen/DbmsDetails.R#L92) but it does not seem to work at our end. 

I appreciate your advice on this.

**Comment by schuemie** [comment]
@anthonysena : I know you have been working on this. Could you help @writetoritu ?

**Comment by anthonysena** [comment]
Sure - there was some discussion around DatabaseConnector & SSL on the forums here:

http://forums.ohdsi.org/t/database-connector-cannot-connect-to-amazon-redshift-even-though-rpostgresql-can/1119

In that thread, there is an example of using the 'extraSettings' to specify an SSL connection. Just to confirm: you have enabled SSL on your PostgreSQL server and have tested the connection outside of DatabaseConnector, correct? If that works, then DatabaseConnector should work as well by using the 'extraSettings'.

**Comment by writetoritu** [comment]
Thank you for your responses @schuemie  @anthonysena 
I had to uninstall and reinstall the databaseconnector package as I was using a much older version. 
Then, had to add `extraSettings="ssl=true&sslmode=verify-full` to the connectionString and it worked perfectly for me!
