### ISSUE TITLE
java.lang.NullPointerException (while retrieving records with null values)

### ISSUE THREAD

**Issue by writetoritu** [OHDSI/DatabaseConnector#46]
I recently installed to the latest version of the `DatabaseConnector` package and I am trying to execute a simple query on Postgres (which was working fine with the older version of the package)

```
querySql.ffdf(con,' select visit_end_date, visit_start_date from pedsnet.visit_occurrence where visit_end_date is null limit 10')
``` 
I get the following error `Error: Error executing SQL: java.lang.NullPointerException`

The query works fine otherwise (i.e. when run directly on the database) and returns some records with null values in one of the columns. 

Please let me know if I am missing something. 

I tried running different queries and it looks like the ones that return NULL values in any date field do not execute.

**Comment by schuemie** [comment]
Thanks! You were right that NULL values in date fields were the problem. I fixed the code. Could you try the latest version?

**Comment by writetoritu** [comment]
looks like its working! 

Thanks for the quick fix.
