### ISSUE TITLE
Undefined connectionDetails object reference

### ISSUE THREAD

**Issue by schuemie** [OHDSI/DatabaseConnector#48]
@alondhe : this connectionDetails object reference does not appear to be valid. Could you fix it?:

https://github.com/OHDSI/DatabaseConnector/blob/0c8d63fac88189a589968f4a27be9b993e7d3637/R/InsertTable.R#L451

**Comment by alondhe** [comment]
Sorry @schuemie , didn't see this until now. I'll fix this and also add in a note about append mode needing the ddl_admin permission for PDW.

**Comment by alondhe** [comment]
@schuemie this may be a bit more complex than I thought. I forgot insertTable only uses open Connections, it doesn't have the full connectionDetails object in scope. I've seen mention of being able to grab database metadata and ultimately the jdbc URL from a Connection object via Java interface: https://stackoverflow.com/questions/5718952/how-to-get-database-url-from-java-sql-connection. But not sure if there's an R wrapper for this. Do you know?

**Comment by schuemie** [comment]
Good idea. You can just use rJava to talk to Java:
```r
databaseMetaData <- rJava::.jcall(connection$jConnection, "Ljava/sql/DatabaseMetaData;", "getMetaData")
url <- rJava::.jcall(databaseMetaData, "Ljava/lang/String;", "getURL")
```
