### ISSUE TITLE
JDK 10: warnings with connect

### ISSUE THREAD

**Issue by alondhe** [OHDSI/DatabaseConnector#61]
Hi @schuemie,

It looks like R 3.5 only seems to work with JDK 10, but installing JDK 10 seems to introduce a few new wrinkles, one of which is with connect() and Redshift:

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.amazon.jdbc.classloader.JarInJarClassLoader (file:/home/alondhe2/R/x86_64-redhat-linux-gnu-library/3.5/DatabaseConnectorJars/java/RedshiftJDBC4-1.2.10.1009.jar) to field java.net.URL.factory
WARNING: Please consider reporting this to the maintainers of com.amazon.jdbc.classloader.JarInJarClassLoader
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

This doesn't break anything, so not a huge problem, but the warning message hints that future JDKs could prevent the connection from happening without a fix to java.net.URL.factory.

Thanks,
Ajit

**Comment by schuemie** [comment]
Hi @alondhe . Why do you say R 3.5 requires Java 10? I have R 3.5.1 running with Java 8 without trouble.

It seems the real culprit here is the RedShift JDBC jar. Perhaps there's a newer version of the driver where this problem is fixed?

**Comment by alondhe** [comment]
It worked with JDK 8? Hmm, not sure why we couldn't get it to work across both Windows and Linux. Never mind on R 3.5 requiring JDK 10 then. 

There is a newer Redshift driver, I'll fork the package and try updating it and testing if it provides the same warnings.
