### ISSUE TITLE
Possible issue: NULLS handled as 0s

### ISSUE THREAD

**Issue by alondhe** [OHDSI/DatabaseConnector#62]
Something that could be an issue: querying records with NULL values against SQL Server on a Windows machine seems to be producing 0s for the NULL values when you run querySql().

This doesn't happen for me using PDW/Windows or SQL Server/RedHat. Need to dig into this more, but @schuemie have you seen anything like this?

Edit: Anthony Molinaro confirms he's getting 0s for NULL values in SQL Server/Windows

**Comment by schuemie** [comment]
Nope, no clue what that could be, and certainly undesired behavior.

**Comment by alondhe** [comment]
Per @schuemie -- this was due to an old SQL JDBC jar file being locked in our .RData files. This older JDBC must've had the bug. But now we're actually using the latest JDBC jar file and it's working perfectly.
