### ISSUE TITLE
Warn when inserting tables with potential illegal field names or table names

### ISSUE THREAD

**Issue by schuemie** [OHDSI/DatabaseConnector#75]
Many SQL dialects have reserved words that cannot be used as field names or table names (e.g. 'rowid' on Oracle). It would be good if DatabaseConnector would throw a warning if it detects such a name when inserting a table.

**Comment by ericaVoss** [comment]
Ha, you beat me to the bunch, but I was going to state it differently.

I just tried to insert a table that had a column OR in it, and Postgres choked.

What if you "" the column names?  Although I think Postgres likes "" and SQL Server likes []

**Comment by NEONKID** [comment]
@ericaVoss 
I agree. A typical example is named user. When I enabled the authentication method in ATLAS, I experienced problems when creating and using the ```user``` table.

**Comment by ablack3** [comment]
I came up with a solution for this and commited my changes here: https://github.com/ablack3/DatabaseConnector

The solution consists of

- A csv file with SQL reserved words in a new folder called dev (short for development)
- A script in the dev folder that adds the sql reserved words to the package data folder
- A function called `isSqlRerservedWord` that takes a character vector and checks for SQL reserved words
- Calls to `isSqlRerservedWord` inside each of the two `insertTable` methods


I'm fairly new to collaboration using git, github, and OHDSI so let me know if you think my solution will work and how to proceed. I should have committed on a separate branch but accidentally committed it to master.

**Comment by schuemie** [comment]
Thanks! I'm travelling right now, but will respond in a week or so.

**Comment by schuemie** [comment]
Looks good. Would you mind moving the csv file to the extras folder (that is where we put our dev stuff)? After that, please create a pull request.
