### ISSUE TITLE
Output bigint values as integer64 instead of numeric?

### ISSUE THREAD

**Issue by schuemie** [OHDSI/DatabaseConnector#81]
Native R does not support 32 bit integers (add sarcastic comment here), so until now we convert BIGINT values to `numeric`. The mantissa of R's numeric type only has 53 bits of precision, so there's a real danger of losing information.

There is the integer64 type in the [bit64 package](https://cran.r-project.org/web/packages/bit64/index.html) that other DB interface packages use to store BIGINTs. This class does come with a warning:

> WARNING: do not use them as replacement for 32bit integers, integer64 are not supported for subscripting by R-core and they have different semantics when combined with double, e.g. integer64 + double => integer64. Class integer64 can be used in vectors, matrices, arrays and data.frames. 

Should we output BIGINT values to integer64?

**Comment by chandryou** [comment]
I used to prefer not to use bit64 package (I just didn't want to add some other packages to the OHDSI core library ). But I'm not sure. 

Pros for integer64 type: minimizing the risk of loss of information for BIGINT in DB, as you said. 
Cons for integer64 type: I don't know how long this package can be maintained, and how stable this package is.

**Comment by NEONKID** [comment]
@schuemie In DBMS, BIGINT supports a range of up to 2 ^ 63 - 1 in most cases. Therefore, we can not express all ranges of BIGINT with INT supported by R.

As mentioned in the #72, there are actually classes that support the BIGINT range in the ```bit64``` package or the ```gmp``` package. but I do not know which is better package either.

**Comment by schuemie** [comment]
Added to v4.0.0
