### ISSUE TITLE
Opening Connections to BigQuery

### ISSUE THREAD

**Issue by CartWill** [OHDSI/DatabaseConnector#83]
I've been trying to use the connector to open a connection to BigQuery but i get a lot of errors.  

Error in rJava::.jcall(p, "Ljava/lang/Object;", "setProperty", names(properties)[i],  : 
  java.lang.NullPointerException

The commits say it's been updated for the Simba driver but it doesn't look like it's forming a connection string that works with it.  Simba's documentation has the connection string being build as jdbc:bigquery: but the code in the Connect.R has it being built as jdbc:BQDriver:.  Also, the connection string has a ? as the separator when bringing in the extraSettings but Simba's documentation has just a ; separating parameters.

**Comment by schuemie** [comment]
@pavgra : Could you take a look at this? I don't have a test environment for BigQuery.

**Comment by t-abdul-basser** [comment]
See connectionString below...
```
connectionDetails <- createConnectionDetails(
  dbms="bigquery", 
  connectionString="jdbc:bigquery://https://www.googleapis.com/bigquery/v2:443;ProjectId=YOUR_PROJECT_ID;OAuthType=0;OAuthServiceAcctEmail=bigquery-admin@atlas-iap.iam.gserviceaccount.com;OAuthPvtKeyPath=C:/bigquery-admin-service-acc-key.json;Timeout=1000",
  user="",
  password='',
  pathToDriver = "PATH_TO_FOLDER_WITH_BQ_SIMBA_DRIVERS"
)
```
Answered by Pavel [here](http://forums.ohdsi.org/t/achilles-and-bigquery/6216/2).
