### ISSUE TITLE
Port support for SQL Server with user/password auth

### ISSUE THREAD

**Issue by aaron0browne** [OHDSI/DatabaseConnector#9]
The user/password connection string (using the `jtds` driver) fails to test for and include the port.

https://github.com/OHDSI/DatabaseConnector/blob/master/R/DatabaseConnector.R#L148

**Comment by schuemie** [comment]
I added the parameter (see c2512de89a30f7bb2ca3812ccaa0107d8c27dbe9). Let me know if this fixes the problem.

**Comment by aaron0browne** [comment]
Still getting an error, believe it is related to the jtds url format. See my comment [here](https://github.com/OHDSI/DatabaseConnector/commit/c2512de89a30f7bb2ca3812ccaa0107d8c27dbe9#commitcomment-9940632)

**Comment by schuemie** [comment]
Oops, yes, you're right. Can you give it another try? (See 94757cce72d948797d69383d9be4cb7ce7ce18a2)

**Comment by aaron0browne** [comment]
Another comment re: database/schema

https://github.com/OHDSI/DatabaseConnector/commit/94757cce72d948797d69383d9be4cb7ce7ce18a2#commitcomment-9947882

**Comment by schuemie** [comment]
You can specify the database in the `schema` parameter, and the `connect()` function will automatically switch to the database (see this [line](https://github.com/OHDSI/DatabaseConnector/blob/master/R/DatabaseConnector.R#L157)). (The words 'Database' and 'Schema' tend to have different meaning across platforms, as you also see from the [lengthy discussion](http://forums.ohdsi.org/t/getting-rid-of-dbo-in-our-parameterized-sql/267) we've had previously.)

**Comment by aaron0browne** [comment]
Great. This is now working.
