### ISSUE TITLE
Redshift truncate table error

### ISSUE THREAD

**Issue by alondhe** [OHDSI/DatabaseConnector#90]
Hi @schuemie ,

Can you try this on your end? I'm not sure why this error is happening using DatabaseConnector, but not happening when using SqlWorkbench with the same Redshift JDBC driver. I'm trying to run a simple truncate table statement using executeSqlI(), but getting the below errorReport. I tried this on Windows and RHEL, using both the latest Redshift JDBC Jar in DatabaseConnectorJars and a previous version of the JDBC Jar. AWS did update Redshift cluster images recently, perhaps that broke something. 

```
DBMS:
redshift

Error:
java.sql.SQLException: [Amazon][JDBC](10040) Cannot use commit while Connection is in auto-commit mode.

SQL:
TRUNCATE TABLE results_3121.heracles_analysis

R version:
R version 3.5.2 (2018-12-20)

Platform:
x86_64-redhat-linux-gnu

Attached base packages:
- stats
- graphics
- grDevices
- utils
- datasets
- methods
- base
```

**Comment by schuemie** [comment]
Yes, I can reproduce that error. It seems to be a 'feature' of the new JDBC driver. Install DatabaseConnectorJars v1.0.0 and the problem goes away.

**Comment by aharden** [comment]
@schuemie The update in `develop` unblocked the same issue I was seeing.  Thanks!
