### ISSUE TITLE
IO error when the query timeouts on a large table  

### ISSUE THREAD

**Issue by fqzhao** [OHDSI/DatabaseConnector#91]
I run Achilles on a large dataset where the measurement table contains 40 million records. One of the task (for measurement) failed with error "Error: Error executing SQL: org.postgresql.util.PSQLException: An I/O error occurred while sending to the backend"

I adjusted parameters in database server but didn't work. I looked into the source and googled, found it seems to be a issue related to socketTimeout settings in postgresql jdbc driver.

So I was wondering if set socketTimeout to a larger value could fix this issue.

**Comment by mjeph** [comment]
I am also running into this issue when running Achilles on a Postgres database. It's a pretty consistent timeout at around 5 minutes of a query when running Achilles. Measurement tables is gigantic, and some of the queries in Achilles will just run long. I have no way of avoiding this issue without deleting the query from running in Achilles.

**Comment by schuemie** [comment]
Could anyone who experiences this problem give the following code a try? If it works I can bake it into DatabaseConnector. In this code, `connection` is the connection object created using the DatabaseConnector `connect` function, and 10 * 60 * 1000 refects 10 minutes in milliseconds:

```r
executor <- rJava::J("java.util.concurrent.Executors")$newFixedThreadPool(as.integer(1))
executor <- rJava::.jcast(executor, "java.util.concurrent.Executor")
rJava::.jcall(connection@jConnection, "V", "setNetworkTimeout", executor, as.integer(10 * 60 * 1000))
```

**Comment by mjeph** [comment]
@schuemie Not sure where you're referring to try the code you have.
I've tried digging into the code a little bit in DatabaseConnector where it's being used by the https://github.com/OHDSI/Achilles code. So I've only taken a look at DatabaseConnector::createConnectionDetails and DatabaseConnector::connect which I believe makes the postgres connection details and establishes the connection for queries. I've tried using `extraSettings` parameter and that didn't work. I tried hardcoding my connection string like this:
```
  connection <- DatabaseConnector::connect(dbms = "postgresql",
     connectionString = "jdbc:postgresql://localhost:5432/db?user=postgres&password=abc123&socketTimeout=0&connectTimeout=0"
```
The connection string I followed from https://jdbc.postgresql.org/documentation/head/connect.html. This doesn't seem to work either. All attempts error at around 5minutes/300seconds/300000ms.

Let me know if I should try something specific.

**Comment by schuemie** [comment]
Ah, I see, you never have the connection object in your control when using ACHILLES.

I've created a timeout branch where I [hard-coded the setting of the timeout](https://github.com/OHDSI/DatabaseConnector/commit/fd6ec87bf9e1a0ed44eaca8652bedf0d839fdc41). Could you give that a try? If it works I'll make a cleaner implementation. Install the modified version of DatabaseConnector using;

```r
devtools::install_github("ohdsi/DatabaseConnector", ref = "timeout")
```

and then run ACHILLES.

**Comment by mjeph** [comment]
Doesn't seem to work, and I'm trying to verify I have the new code installed, but I can't seem to verify. Would this be the right way to do it in R?

`library(DatabaseConnector)`
`print(DatabaseConnector::connectUsingJdbcDriver)`
When I type the code above in R command line, I get 
`Error: 'connectUsingJdbcDriver' is not an exported object from 'namespace:DatabaseConnector'`
so I can't be 100% sure I have the new code installed although I am referencing "timeout" in my install script so I do have confidence it worked.

**Comment by schuemie** [comment]
For functions that are not exported you need a triple colon:

```r
print(DatabaseConnector:::connectUsingJdbcDriver)
```
(you also don't really need the `print`)

Dealing with timeouts in JDBC seems very convoluted. If this doesn't work I'll try setting the timeout at the statement level:
```java
java.sql.Statement.setQueryTimeout(int timeout)
```

**Comment by mjeph** [comment]
Yup! I have it installed properly. I see your new code:
`    executor <- rJava::J("java.util.concurrent.Executors")$newFixedThreadPool(as.integer(1))
    executor <- rJava::.jcast(executor, "java.util.concurrent.Executor")
    rJava::.jcall(connection@jConnection, "V", "setNetworkTimeout", 
        executor, as.integer(10 * 60 * 1000))`

**Comment by schuemie** [comment]
Hmmm, setQueryTimeout does not look promising, as it should be unlimited by default. I'm not sure what to try next. Any ideas?

**Comment by mjeph** [comment]
That was the other thing I was thinking about with all of this. Not sure why it would be timing out at 5 minutes. I've had queries last over 5 minutes outside of running R code (e.g. a query I executed) so I don't think it's a server setting. I also have done this on a local Postgres database and a Postgres compatible Aurora database on AWS. Both have had the same effect. I'm not sure what to try next either. I'll think about this more.

Documentation from https://jdbc.postgresql.org/documentation/head/connect.html:
loginTimeout = int
Specify how long to wait for establishment of a database connection. The timeout is specified in seconds.

connectTimeout = int
The timeout value used for socket connect operations. If connecting to the server takes longer than this value, the connection is broken. The timeout is specified in seconds and a value of zero means that it is disabled.

socketTimeout = int
The timeout value used for socket read operations. If reading from the server takes longer than this value, the connection is closed. This can be used as both a brute force global query timeout and a method of detecting network problems. The timeout is specified in seconds and a value of zero means that it is disabled.

**Comment by schuemie** [comment]
@mjeph : Is this issue still unresolved?

**Comment by fqzhao** [comment]
Hi,

This issue is actually caused by macOS based docker network after
investigation.  On linux everything is fine. So it is not a real issue.

Thanks,
Franklin


Martijn Schuemie ***@***.***> 于2021年4月19日周一 下午5:14写道：

**Comment by schuemie** [comment]
Thanks for the update! I'll close this issue now.
